homeslands/order

app/order-api/src/order-item/order-item.controller.spec.ts
app/order-api/src/order-item/order-item.controller.ts
app/order-api/src/order-item/order-item.dto.ts
app/order-api/src/order-item/order-item.module.ts
app/order-api/src/order-item/order-item.service.spec.ts
app/order-api/src/order-item/order-item.service.ts
app/order-api/src/order-item/order-item.utils.ts
app/order-api/src/order/order.controller.ts
app/order-api/src/order/order.dto.ts
app/order-api/src/order/order.scheduler.ts
app/order-api/src/order/order.service.spec.ts
app/order-api/src/order/order.service.ts
app/order-api/src/order/order.utils.ts
app/order-api/src/order/order.validation.ts
app/order-api/src/tracking-order-item/tracking-order-item.dto.ts
app/order-api/src/tracking-order-item/tracking-order-item.entity.ts
app/order-api/src/tracking-order-item/tracking-order-item.mapper.ts
app/order-api/src/tracking/tracking.scheduler.spec.ts
app/order-api/src/tracking/tracking.service.spec.ts
app/order-api/src/tracking/tracking.service.ts

Add update order api

---

app/order-api/src/menu-item/menu-item.utils.ts
app/order-api/src/menu-item/menu-item.validation.ts
app/order-api/src/order-item/order-item.controller.spec.ts
app/order-api/src/order-item/order-item.module.ts
app/order-api/src/order-item/order-item.service.spec.ts
app/order-api/src/order-item/order-item.service.ts
app/order-api/src/order/order.controller.ts
app/order-api/src/user/user.utils.ts

update create/delete order item
- Update menu item stock after create/delete order item

update create/delete order item

---

app/order-api/src/order/order.service.ts
app/order-api/src/table/table.controller.ts
app/order-api/src/table/table.dto.ts
app/order-api/src/table/table.module.ts
app/order-api/src/table/table.service.spec.ts
app/order-api/src/table/table.service.ts
app/order-api/src/table/table.subscriber.ts
app/order-api/src/table/table.utils.ts
app/order-api/src/table/table.validation.ts
app/order-ui/package-lock.json
app/order-ui/src/app/layouts/system/SystemLayout.tsx
app/order-ui/src/app/layouts/system/components/app-header.tsx
app/order-ui/src/components/app/form/profile-form.tsx
app/order-ui/src/router/routes.ts

update create/update/delete table api

update create/update/delete table api

---

app/order-api/src/menu-item/menu-item.entity.ts
app/order-api/src/menu/menu.controller.spec.ts
app/order-api/src/menu/menu.dto.ts
app/order-api/src/menu/menu.service.spec.ts
app/order-api/src/menu/menu.service.ts

add promotion query to get promotional products

add promotion query to get promotional products

---

app/order-ui/src/app/client/cart/page.tsx
app/order-ui/src/app/client/payment/page.tsx
app/order-ui/src/components/app/dialog/cancel-order-dialog.tsx
app/order-ui/src/components/app/tabs/system-menu.tabs.tsx
app/order-ui/src/components/app/tabscontent/customer-order.tabscontent.tsx
app/order-ui/src/hooks/use-order.ts

Temporarily disable the internal wallet on the customer page and system page

---

app/order-api/src/authority-group/authority-group.controller.ts
app/order-api/src/authority-group/authority-group.dto.ts
app/order-api/src/authority-group/authority-group.exception.ts
app/order-api/src/authority-group/authority-group.service.ts
app/order-api/src/authority-group/authority-group.validation.ts
app/order-api/src/authority/authority.controller.spec.ts
app/order-api/src/authority/authority.controller.ts
app/order-api/src/authority/authority.dto.ts
app/order-api/src/authority/authority.service.spec.ts
app/order-api/src/authority/authority.service.ts
app/order-api/src/authority/authority.validation.ts

- Add CRUD authority API
- Add CRUD authority group API

update authority, authority group api

---

app/order-api/src/menu/menu.controller.spec.ts
app/order-api/src/menu/menu.service.spec.ts
app/order-api/src/menu/menu.service.ts
app/order-api/src/menu/menu.validation.ts

**Update menu service**:
- Use transaction to manage transaction and log error

Update menu service

---

app/order-api/public/templates/invoice.ejs
app/order-api/src/invoice-item/invoice-item.dto.ts
app/order-api/src/invoice-item/invoice-item.entity.ts
app/order-api/src/invoice/invoice.dto.ts
app/order-api/src/invoice/invoice.entity.ts
app/order-api/src/invoice/invoice.scheduler.ts
app/order-api/src/invoice/invoice.service.ts
app/order-api/src/migrations/1744358718217-add-vocher-value-and-id-for-invoice-entity.ts
app/order-api/src/migrations/1744359003564-add-promotion-value-and-id-for-invoice-item-entity.ts
app/order-api/src/order/order.scheduler.ts
app/order-ui/src/app/system/chef-order/components/chef-order-item-detail.tsx
app/order-ui/src/app/system/chef-order/components/chef-order-item-list.tsx
app/order-ui/src/app/system/home/overview-detail-page.tsx
app/order-ui/src/app/system/order-management/customer-information.tsx
app/order-ui/src/app/system/order-management/order-item-detail.tsx
app/order-ui/src/app/system/order-management/order-item-list.tsx
app/order-ui/src/components/app/dialog/create-order-tracking-by-robot-dialog.tsx
app/order-ui/src/components/app/dialog/create-order-tracking-by-staff-dialog.tsx
app/order-ui/src/components/app/sheet/chef-order-item-detail-sheet.tsx
app/order-ui/src/components/app/sheet/order-item-detail-sheet.tsx
app/order-ui/src/components/ui/dialog.tsx
app/order-ui/src/index.css
app/order-ui/src/locales/vi/dashboard.json
app/order-ui/src/locales/vi/menu.json
app/order-ui/src/types/revenue.type.ts

[update: promotion and voucher for invoice](https://github.com/homeslands/order/commit/456eab6926fd99a33045d618ae5c2b6ed27497e6)
[Updte chef order page, order management page](https://github.com/homeslands/order/commit/115b38b9a762ab87ef57294214506e4b14a0c77f)

update: promotion and voucher for invoice (be); Updte chef order page, order management page(fe)

---

.github/workflows/deploy-staging.yml

Task Id: GC-20
Description:
+ Update deployment file

* ParentId: GC-19 (2)

---

.github/workflows/deploy-dev.yml
.gitignore

Task Id: GC-22
Description:
+ Update dev workflow

* ParentId: GC-21 (1)

---

app/order-api/src/job/job.recovery.ts

Task Id: GC-27
Description:
+ Fix job_tbl table does not exist

* ParentId: GC-24 (1)

---

app/order-api/src/app/app.module.ts
app/order-api/src/app/base.dto.ts
app/order-api/src/gift-card-modules/card/card.controller.spec.ts
app/order-api/src/gift-card-modules/card/card.controller.ts
app/order-api/src/gift-card-modules/card/card.exception.ts
app/order-api/src/gift-card-modules/card/card.mapper.ts
app/order-api/src/gift-card-modules/card/card.service.spec.ts
app/order-api/src/gift-card-modules/card/card.service.ts
app/order-api/src/gift-card-modules/card/card.validation.ts
app/order-api/src/gift-card-modules/card/dto/card-response.dto.ts
app/order-api/src/gift-card-modules/card/dto/create-card.dto.ts
app/order-api/src/gift-card-modules/card/dto/find-all-card.dto.ts
app/order-api/src/gift-card-modules/card/dto/update-card.dto.ts
app/order-api/src/gift-card-modules/card/entities/card.entity.ts
app/order-api/src/gift-card-modules/gift-card.module.ts
app/order-api/src/migrations/1747590051505-init-card.ts

Task Id: GC-03
Description:
+ Implement CRUD Card API

* ParentId: GC-01-BE (1)

---

app/order-api/public/templates/voucher-ticket.ejs
app/order-api/src/product/product.controller.spec.ts
app/order-api/src/product/product.service.spec.ts
app/order-api/src/voucher/voucher.controller.spec.ts
app/order-api/src/voucher/voucher.controller.ts
app/order-api/src/voucher/voucher.dto.ts
app/order-api/src/voucher/voucher.module.ts
app/order-api/src/voucher/voucher.service.spec.ts
app/order-api/src/voucher/voucher.service.ts
app/order-api/src/voucher/voucher.validation.ts

Task Id: VC-02-BE
Description:
+ Create api export voucher pdf

* ParentId: VC-01-BE (1)

---

app/order-api/src/voucher/voucher.service.ts

Task Id: VC-03-BE
Description:
+ Fix get all voucher for manager: order by code ASC

* ParentId: VC-01-BE (2)

---

.github/workflows/deploy-dev.yml
app/order-api/src/gift-card-modules/card/card.controller.spec.ts
app/order-api/src/gift-card-modules/card/card.service.spec.ts

Task Id: GC-30
Description:
+ Fix unit test error

* ParentId: GC-01-BE (2)

---

.github/workflows/deploy-dev.yml

Task Id: GC-30
Description:
+ Fix workflow is not running

* ParentId: GC-01-BE (4)

---

.github/workflows/deploy-dev.yml

Task Id: GC-30
Description:
+ Remove condition on workflow dev

* ParentId: GC-01-BE (5)

---

app/order-api/src/invoice/invoice.service.ts

Task Id: IV-02-BE
Description:
+ Fix subtotalBeforeVoucher value

* ParentId: IV-01-BE (1)

---

app/order-api/src/invoice/invoice.service.ts

Task Id: IV-03-BE 
Type: Development 
Description: 
+ Fix voucher value

* ParentId: IV-01-BE (2 + 3)

---

app/order-api/src/voucher/voucher.service.ts
app/order-api/src/voucher/voucher.validation.ts

Task Id: VC-04-BE
Description:
+ Validate voucher value type percent order in create, bulkCreate, update voucher

* ParentId: VC-01-BE (3)

---

app/order-api/src/voucher/voucher.mapper.ts

Task Id: VC-05-BE
Description:
+ Fix date in response: startDate, endDate

* ParentId: VC-01-BE (4)

---

app/order-ui/src/components/app/sheet/staff-voucher-list-sheet-in-update-order.tsx
app/order-ui/src/components/app/sheet/voucher-list-sheet-in-update-order.tsx
app/order-ui/src/components/app/sheet/voucher-list-sheet.tsx

Task Id: VOUCHER-01-FE
Description:
+ Call voucher for order api base on order owner
+ Fix voucher end date display error

* ParentId: VOUCHER-01-FE (6)

---

app/order-ui/src/app/system/gift-card/DataTable/columns/gift-card-columns.tsx
app/order-ui/src/app/system/gift-card/page.tsx
app/order-ui/src/types/gift-card.type.ts

Task Id: GC-04
Description:
- Fix Bug: BUG-023, BUG-020

* ParentId: GC-01-FE (3)

---

app/order-api/src/order-item/order-item.controller.spec.ts
app/order-api/src/order-item/order-item.module.ts
app/order-api/src/order-item/order-item.service.spec.ts
app/order-api/src/order-item/order-item.service.ts
app/order-api/src/voucher/voucher.utils.ts

Task Id: VC-06-BE
Description:
+ Revalidate min value order for voucher when delete, change amount order item

* ParentId: VC-01-BE (5)

---

app/order-api/public/templates/invoice.ejs

Task Id: IV-02-BE
Description:
+ Fix invoice template

* ParentId: IVB-01-BE (1)

---

app/order-api/src/payment/payment.service.ts

Task Id: VCB-02-BE
Description:
- By pass pay when order subtotal < 2000 with payment method CASH

* ParentId: VCB-01-BE (1)

---

.github/workflows/deploy-dev.yml
app/order-api/src/app/app.module.ts
app/order-api/src/app/base.dto.ts
app/order-api/src/gift-card-modules/card/card.controller.spec.ts
app/order-api/src/gift-card-modules/card/card.controller.ts
app/order-api/src/gift-card-modules/card/card.exception.ts
app/order-api/src/gift-card-modules/card/card.mapper.ts
app/order-api/src/gift-card-modules/card/card.service.spec.ts
app/order-api/src/gift-card-modules/card/card.service.ts
app/order-api/src/gift-card-modules/card/card.validation.ts
app/order-api/src/gift-card-modules/card/dto/card-response.dto.ts
app/order-api/src/gift-card-modules/card/dto/create-card.dto.ts
app/order-api/src/gift-card-modules/card/dto/find-all-card.dto.ts
app/order-api/src/gift-card-modules/card/dto/update-card.dto.ts
app/order-api/src/gift-card-modules/card/entities/card.entity.ts
app/order-api/src/gift-card-modules/gift-card.module.ts
app/order-api/src/migrations/1747590051505-init-card.ts

Task Id: GC-03
Description:
+ Implement CRUD Card API

* ParentId: GC-01-BE (1) 

---

app/order-api/src/order-item/order-item.service.ts
app/order-api/src/order/order.service.ts
app/order-api/src/order/order.utils.ts

Task Id: OR-509-BE
Description:
+ Change remove to softRemove when delete order, order item

* ParentId: OR-509-BE (1)

---

.deploy/prod-for-staff/docker-compose.yml
.github/workflows/deploy-prod-for-staff.yml

Task Id: GC-40
Description:
+ Setup workflow for prod-staff env

 * ParentId: GC-39 (1)

---

.github/workflows/deploy-prod-for-staff.yml

Task Id: GC-40
Description:
+ Fix .deploy/cloud/.env: No such file or directory

* ParentId: GC-39 (3)

---

app/order-api/src/order/order.service.ts

Task Id: OR-509-BE
Description:
- Change time delete order to 15 minutes

* ParentId: OR-509-BE (2)

---

app/order-api/src/voucher/voucher.service.spec.ts
app/order-api/src/voucher/voucher.service.ts
app/order-api/src/voucher/voucher.utils.ts
app/order-api/src/voucher/voucher.validation.ts

Task Id: VC-517-BE
Description:
- Change: use softRemove when delete voucher
- Verify only user verified email just use verificationIdentity voucher

* ParentId: VC-517-BE (1)

---

app/order-api/src/menu/menu.scheduler.ts

Task Id: MN-511-BE
Description:
- Get isLocked property when auto generate menu

* ParentId: MN-511-BE (1)

---

.deploy/prod-for-staff/docker-compose.yml

Task Id: GC-40
Description:
+ Expose api, ui port

* ParentId: GC-39 (4)

---

app/order-ui/src/app/client/payment/skeleton/page.tsx
app/order-ui/src/app/system/order-history/DataTable/columns/order-history-columns.tsx
app/order-ui/src/app/system/payment/payment-page.tsx
app/order-ui/src/components/app/countdown/OrderCountdown.tsx
app/order-ui/src/locales/en/menu.json
app/order-ui/src/locales/vi/menu.json

Task Id: OR-520-FE
Description:
+ Fix runtime error when authorityGroup.authorities contains null or undefined values
+ Regenerate QR Code on Checkout Page when Order Information Updates

* ParentId: OR-520-FE (1)

---

app/order-api/src/order/order.dto.ts

Task Id: PM-514-BE
Description:
- Add amount in Payment response in order

* ParentId: PM-514-BE (3)

---

app/order-ui/src/app/client/payment/page.tsx
app/order-ui/src/app/layouts/system/SystemLayout.tsx
app/order-ui/src/app/layouts/system/client-view-layout.tsx
app/order-ui/src/app/system/payment/payment-page.tsx
app/order-ui/src/locales/en/toast.json
app/order-ui/src/locales/vi/toast.json
app/order-ui/src/stores/payment-method.store.ts
app/order-ui/src/stores/payment.store.ts
app/order-ui/src/types/store.type.ts
app/order-ui/src/utils/toast.ts

Task Id: OR-520-FE
Description:
+ Fix runtime error when authorityGroup.authorities contains null or undefined values.
+ Regenerate QR Code on Checkout Page when Order Information is updated. Applied for both Customer and Staff sides.

* ParentId: OR-520-FE (2)

---

app/order-ui/src/app/client/cart/page.tsx
app/order-ui/src/components/app/select/table-select.tsx

Task Id: OR-524-FE
Description:
+ Use branch slug from branch store to get table list

* ParentId: OR-524-FE (3+4+5)

---

app/order-api/src/order/order.controller.ts
app/order-api/src/order/order.dto.ts
app/order-api/src/order/order.service.ts
app/order-api/src/order/order.validation.ts

Task Id: OR-511-BE
Description:
- Revert commit (3)

* ParentId: OR-509-BE (4)

---

.github/workflows/deploy-prod-for-staff.yml
.github/workflows/publish-prod-for-staff.yaml

Task Id: GC-46
Description:
+ Create pushlish workflow
+ Update deploy workflow

* ParentId: GC-45 (1)

---

.deploy/prod-for-staff/docker-compose.yml
app/order-api/src/config/cors.config.ts

Task Id: GC-46
Description:
+ Update docker compose
+ Fix CORS

* ParentId: GC-45 (2)

---

app/order-ui/src/app/system/gift-card/DataTable/columns/gift-card-columns.tsx
app/order-ui/src/components/app/dialog/delete-gift-card-dialog.tsx
app/order-ui/src/components/app/sheet/update-gift-card-sheet.tsx

Task Id: GC-42
Description:
+ Add tooltip for card title, desc when length too long

* ParentId: GC-42-FE (2)

---

app/order-api/src/auth/auth.controller.ts
app/order-api/src/auth/auth.service.ts
app/order-api/src/auth/auth.validation.ts

Task Id: VM-530-BE
Description:
- Add api resend verify email code for user

* ParentId: VM-530-BE (1)

---

app/order-api/public/templates/mail/verify-email.ejs
app/order-api/src/auth/auth.controller.ts
app/order-api/src/auth/auth.dto.ts
app/order-api/src/auth/auth.mapper.ts
app/order-api/src/auth/auth.service.ts
app/order-api/src/auth/entity/verify-email-token.entity.ts
app/order-api/src/mail/mail.service.ts

Task Id: VM-530-BE
Description:
- Add verify email response

* ParentId: VM-530-BE (2)

---

app/order-ui/src/api/auth.ts
app/order-ui/src/components/app/card/user-profile-card.tsx
app/order-ui/src/components/app/dialog/send-verify-email-dialog.tsx
app/order-ui/src/components/app/tabscontent/customer-info.tabscontent.tsx
app/order-ui/src/components/ui/countdown-timer.tsx
app/order-ui/src/stores/user.store.ts
app/order-ui/src/types/profile.type.ts
app/order-ui/src/types/store.type.ts

Task Id: VERIFY-532-FE
Description:
+ Handle resend email verification with expire time

* ParentId: VERIFY-532-FE (2)

---

app/order-api/src/voucher/voucher.service.spec.ts
app/order-api/src/voucher/voucher.service.ts

Task Id:  VC-534-BE
Description:
- Change remove to softRemove when delete voucher

* ParentId: VC-534-BE (1)

---

app/order-api/src/order/order.controller.ts
app/order-api/src/order/order.dto.ts
app/order-api/src/order/order.service.ts
app/order-api/src/order/order.validation.ts

Task Id: OR-533-BE
Description:
Separate api update order:
- Update order: table, type, note
- Update voucher order

* ParentId: OR-533-BE (1)

---

app/order-ui/src/app/client/gift-card/components/gift-card-item.tsx
app/order-ui/src/app/layouts/client/components/bottom-bar.tsx
app/order-ui/src/components/app/dialog/gift-card-selected-dialog.tsx
app/order-ui/src/components/app/drawer/gift-card-selected-drawer.tsx
app/order-ui/src/locales/en/sidebar.json
app/order-ui/src/locales/vi/sidebar.json

Task Id: GC-47, GC-48
Type: Fix Bug
Description:
- add CoinsIcon and update translations for gift card feature
- add giftcard to sidebar bottom

* ParentId: GC-05-FE (5)

---

app/order-ui/src/components/app/sheet/staff-voucher-list-sheet-in-update-order.tsx

Task Id: OR-534-FE
Description:
+ Update voucher list when update order in staff role.

* ParentId: OR-534-FE (2)

---

app/order-ui/src/app/client/order-history/page.tsx
app/order-ui/src/components/app/dialog/create-order-dialog.tsx
app/order-ui/src/components/app/drawer/cart-drawer.tsx
app/order-ui/src/components/app/select/index.tsx
app/order-ui/src/components/app/select/system-table-select-in-cart-drawer.tsx
app/order-ui/src/locales/vi/menu.json

Task Id: OR-534-FE
Description:
+ Add order note field in cart drawer in staff role

* ParentId: OR-534-FE (3)

---

app/order-api/src/order/order.controller.ts
app/order-api/src/order/order.dto.ts
app/order-api/src/order/order.service.ts
app/order-api/src/order/order.validation.ts

Task Id: OR-533-BE
Description:
Separate api update order:
- Update order: table, type, note
- Update voucher order

* ParentId: OR-533-BE

---

app/order-api/src/auth/auth.service.spec.ts
app/order-api/src/gift-card-modules/balance/balance.controller.spec.ts
app/order-api/src/gift-card-modules/balance/balance.service.spec.ts
app/order-api/src/gift-card-modules/card-order/card-order.controller.spec.ts
app/order-api/src/gift-card-modules/card-order/card-order.service.spec.ts
app/order-api/src/gift-card-modules/card-order/card-order.service.ts
app/order-api/src/gift-card-modules/card-order/card-order.validation.ts
app/order-api/src/gift-card-modules/card-order/dto/card-order-response.dto.ts
app/order-api/src/gift-card-modules/card-order/dto/create-card-order.dto.ts
app/order-api/src/gift-card-modules/card-order/entities/card-order.entity.ts
app/order-api/src/gift-card-modules/gift-card/gift-card.controller.spec.ts
app/order-api/src/gift-card-modules/gift-card/gift-card.controller.ts
app/order-api/src/gift-card-modules/gift-card/gift-card.service.spec.ts
app/order-api/src/gift-card-modules/receipient/recipient.controller.spec.ts
app/order-api/src/migrations/v3.0.0-1749104557354-init-card-order.ts

Task Id: GC-36
Description:
+ Fixed: unit test error

* ParentId: GC-08-BE (5)

---

app/order-ui/src/app/system/menu/components/system-menus-in-update-order.tsx
app/order-ui/src/app/system/menu/components/system-menus.tsx
app/order-ui/src/app/system/update-order/components/update-note.tsx
app/order-ui/src/app/system/update-order/components/update-order-note.tsx
app/order-ui/src/app/system/update-order/components/update-quantity.tsx
app/order-ui/src/app/system/update-order/page.tsx
app/order-ui/src/components/app/dialog/create-order-dialog.tsx
app/order-ui/src/components/app/select/order-type-in-update-order-select.tsx
app/order-ui/src/components/app/sheet/staff-voucher-list-sheet-in-update-order.tsx
app/order-ui/src/components/app/tabs/system-menu-in-update-order.tabs.tsx
app/order-ui/src/index.css

Task Id: OR-537-FE
Description:
+ Update voucher sheet logic in update order

* ParentId: OR-537-FE (1)

---

app/order-ui/src/app/system/menu/components/system-menus-in-update-order.tsx
app/order-ui/src/app/system/menu/components/system-menus.tsx
app/order-ui/src/app/system/update-order/components/update-note.tsx
app/order-ui/src/app/system/update-order/components/update-order-note.tsx
app/order-ui/src/app/system/update-order/components/update-quantity.tsx
app/order-ui/src/app/system/update-order/page.tsx
app/order-ui/src/components/app/dialog/create-order-dialog.tsx
app/order-ui/src/components/app/select/order-type-in-update-order-select.tsx
app/order-ui/src/components/app/sheet/staff-voucher-list-sheet-in-update-order.tsx
app/order-ui/src/components/app/tabs/system-menu-in-update-order.tabs.tsx
app/order-ui/src/index.css

Task Id: OR-537-FE
Description:
+ Update voucher sheet logic in update order

* ParentId: OR-537-FE

---

app/order-api/src/user/user.controller.ts

Task Id: GC-36
Description:
+ Fixed: customer can not search user

* ParentId: GC-08-BE (7)

---

app/order-api/src/order/order.service.ts

Task Id: OR-538-BE
Description:
- Fix previous voucher

* ParentId: OR-538-BE

---

app/order-api/src/voucher/voucher.service.ts

Description:
- Fix create voucher type

* ParentId: VC-528-BE (3)

---

app/order-api/src/order-item/order-item.service.ts

Description:
- Fix order item service: update + delete

* ParentId: VC-528-BE (5)

---

app/order-ui/src/app/client/gift-card/components/gift-card-item.tsx
app/order-ui/src/app/client/gift-card/components/gift-card-selected.tsx
app/order-ui/src/app/client/gift-card/components/gift-card-sheet.tsx
app/order-ui/src/app/client/gift-card/components/order-summary.tsx
app/order-ui/src/app/client/gift-card/components/recipient-search-input.tsx
app/order-ui/src/app/client/gift-card/components/single-gift-card-display.tsx
app/order-ui/src/components/app/dialog/gift-card-exists-warning-dialog.tsx
app/order-ui/src/components/app/dialog/gift-card-selected-dialog.tsx
app/order-ui/src/components/app/dialog/index.tsx
app/order-ui/src/components/app/drawer/gift-card-selected-drawer.tsx
app/order-ui/src/locales/en/gift-card.json
app/order-ui/src/locales/vi/gift-card.json
app/order-ui/src/schemas/gift-card.schema.ts

Task Id: GC-51 -> GC-55
Type: Fix Bug
Description:
- Refactor gift card components to use formatCurrency for point and price formatting;
- add gift card existence warning dialog

* ParentId: GC-08-FE(2)

---

app/order-api/public/templates/invoice.ejs
app/order-api/src/invoice/invoice.service.ts
app/order-api/src/order/order.service.ts

Description:
- Fix create order, create invoice, invoice template

* ParentId: VC-528-BE (7)

---

app/order-api/public/templates/invoice.ejs
app/order-api/src/invoice/invoice.service.ts
app/order-api/src/voucher/voucher.service.ts

Description:
- Fix validate voucher public, fix invoice

* ParentId: VC-528-BE (8)

---

app/order-api/package.json
app/order-api/src/config/database.config.ts
app/order-api/src/gift-card-modules/card-order/card-order.controller.spec.ts
app/order-api/src/gift-card-modules/card-order/card-order.controller.ts
app/order-api/src/gift-card-modules/card-order/card-order.service.spec.ts
app/order-api/src/gift-card-modules/card-order/card-order.service.ts
app/order-api/src/gift-card-modules/card-order/card-order.validation.ts
app/order-api/src/gift-card-modules/card-order/dto/card-order-response.dto.ts
app/order-api/src/gift-card-modules/card-order/dto/initiate-card-order-payment.dto.ts
app/order-api/src/gift-card-modules/card-order/entities/card-order.entity.ts
app/order-api/src/gift-card-modules/gift-card.module.ts
app/order-api/src/migrations/v3.0.0-1749614607530-add-slug-field-card-order.ts
app/order-api/src/payment/strategy/bank-transfer.strategy.ts
app/order-api/src/product/product.controller.spec.ts
app/order-api/src/product/product.service.spec.ts

Task Id: GC-32
Description:
+ Make initiate card order payment

* ParentId: GC-09-BE (01)

---

app/order-api/src/order/order.service.ts

Description:
- Fix relation when get all order

* ParentId: VC-528-BE (9)

---

.deploy/cloud/docker-compose.yml
.deploy/dev/docker-compose.yml
.deploy/prod-for-staff/docker-compose.yml
.deploy/staging/docker-compose.yml
app/order-api/src/config/cors.config.ts
app/order-api/src/gift-card-modules/card-order/card-order.enum.ts
app/order-api/src/gift-card-modules/card-order/card-order.listener.ts
app/order-api/src/gift-card-modules/card-order/card-order.subscriber.ts
app/order-api/src/gift-card-modules/card-order/entities/card-order.entity.ts
app/order-api/src/gift-card-modules/card-order/events/card-order-payment-updated.event.ts
app/order-api/src/gift-card-modules/gift-card.module.ts
app/order-api/src/job/job.constants.ts
app/order-api/src/job/job.consumer.ts
app/order-api/src/job/job.controller.spec.ts
app/order-api/src/job/job.module.ts
app/order-api/src/job/job.producer.ts
app/order-api/src/job/job.service.spec.ts
app/order-api/src/job/job.service.ts
app/order-api/src/main.ts
app/order-api/src/payment/payment.constants.ts
app/order-api/src/payment/payment.controller.ts
app/order-api/src/payment/payment.entity.ts
app/order-api/src/payment/payment.service.ts
app/order-api/src/payment/payment.validation.ts

Task Id: GC-32
Description:
+ Auto update card order status after payment completion

* ParentId: GC-09-BE (02)

---

app/order-api/src/order/order.service.ts

Description:
- Fix update voucher order

* ParentId: VC-528-BE (10)

---

app/order-api/src/order/order.service.ts

Description:
- Fix update voucher order 2nd

* ParentId: VC-528-BE (11)

---

app/order-api/src/order/order.service.ts

Description:
- Fix update voucher order 3rd

* ParentId: VC-528-BE (12)

---

app/order-api/src/order-item/order-item.service.ts
app/order-api/src/voucher/voucher.utils.ts

Description:
- Fix update voucher when create new order item for order

* ParentId: VC-528-BE (13)

---

app/order-api/src/order-item/order-item.service.ts
app/order-api/src/voucher/voucher.utils.ts

Description:
- Fix update voucher when create new order item for order 2nd

* ParentId: VC-528-BE (14)

---

app/order-api/src/order-item/order-item.service.ts
app/order-api/src/voucher/voucher.utils.ts

Description:
- Fix update voucher when delete order item for order

* ParentId: VC-528-BE (15)

---

app/order-ui/src/app/system/dishes/product-tab.tsx
app/order-ui/src/app/system/menu/components/cart-content.tsx
app/order-ui/src/components/app/dialog/create-customer-dialog.tsx
app/order-ui/src/components/app/sheet/add-menu-item-sheet.tsx
app/order-ui/src/components/app/sheet/add-product-in-chef-area-sheet.tsx
app/order-ui/src/components/app/sheet/voucher-list-sheet-in-update-order.tsx
app/order-ui/src/components/app/sheet/voucher-list-sheet.tsx
app/order-ui/src/components/app/tabscontent/customer-order.tabscontent.tsx

Task Id: OR-541-FE
Description:
+ Modify min value check when validate voucher
+ Update enable variable when using useProducts hook

* ParentId: OR-541-FE (4)

---

app/order-ui/src/app/system/gift-card/DataTable/columns/gift-card-columns.tsx

Task Id: GC-71
Description:
+ Move action column to the first column

* ParentId: GC-69-FE (01)

---

app/order-ui/src/app/client/cart/page.tsx
app/order-ui/src/app/client/update-order/page.tsx
app/order-ui/src/app/system/payment/payment-page.tsx
app/order-ui/src/components/app/sheet/staff-voucher-list-sheet-in-update-order.tsx
app/order-ui/src/components/app/sheet/staff-voucher-list-sheet.tsx
app/order-ui/src/components/app/sheet/voucher-list-sheet.tsx

Task Id: OR-541-FE
Description:
+ Fix error data in payment page

* ParentId: OR-541-FE (5)

---

app/order-ui/src/components/app/dialog/create-order-dialog.tsx
app/order-ui/src/components/app/sheet/staff-voucher-list-sheet-in-update-order.tsx
app/order-ui/src/components/app/sheet/staff-voucher-list-sheet.tsx

Task Id: OR-541-FE
Description:
+ Fix voucher sheet data error

* ParentId: OR-541-FE (6)

---

app/order-ui/src/app/client/gift-card/components/gift-card-selected.tsx
app/order-ui/src/app/client/gift-card/components/gift-card-sheet.tsx
app/order-ui/src/app/client/gift-card/components/order-summary.tsx
app/order-ui/src/app/client/gift-card/components/receivers-section.tsx
app/order-ui/src/app/client/gift-card/components/single-gift-card-display.tsx
app/order-ui/src/components/ui/quantity-control.tsx

Task Id: GC-37,
Type: Fix Bug
Description:
- GC-74
- GC-75
- GC-76

* ParentId: GC-08-FE (4)

---

app/order-ui/src/app/client/gift-card/checkout/page.tsx
app/order-ui/src/app/client/gift-card/components/gift-card-selected.tsx
app/order-ui/src/app/client/gift-card/components/gift-card-sheet.tsx
app/order-ui/src/app/client/gift-card/components/order-summary.tsx
app/order-ui/src/app/client/gift-card/components/receiver-form.tsx
app/order-ui/src/app/client/gift-card/components/receivers-section.tsx
app/order-ui/src/app/client/gift-card/components/single-gift-card-display.tsx
app/order-ui/src/components/app/dialog/confirm-gift-card-checkout-dialog.tsx
app/order-ui/src/components/ui/quantity-control.tsx

Task Id: GC-37,
Type: Fix Bug
Description:
- GC-74
- GC-75
- GC-76
- GC-83

* ParentId: GC-08-FE (4&5) 

---

app/order-ui/src/app/client/gift-card/checkout/[slug]/components/checkout-header.tsx
app/order-ui/src/app/client/gift-card/checkout/[slug]/components/customer-info.tsx
app/order-ui/src/app/client/gift-card/checkout/[slug]/components/expired-state.tsx
app/order-ui/src/app/client/gift-card/checkout/[slug]/components/gift-card-details-table.tsx
app/order-ui/src/app/client/gift-card/checkout/[slug]/components/loading-state.tsx
app/order-ui/src/app/client/gift-card/checkout/[slug]/components/order-info.tsx
app/order-ui/src/app/client/gift-card/checkout/[slug]/components/payment-method-section.tsx
app/order-ui/src/app/client/gift-card/checkout/[slug]/components/payment-qr-code-section.tsx
app/order-ui/src/app/client/gift-card/checkout/[slug]/page.tsx
app/order-ui/src/components/app/dialog/cancel-gift-card-order-dialog.tsx

Task Id: GC-31,
Type: Fix Bug
Description:
- GC-84
- GC-85

* ParentId: GC-09-FE (5)

---

app/order-ui/src/app/client/gift-card/checkout/[slug]/components/expired-state.tsx
app/order-ui/src/app/client/gift-card/checkout/[slug]/components/loading-state.tsx
app/order-ui/src/app/client/gift-card/checkout/[slug]/page.tsx

Task Id: GC-31,
Type: Fix Bug
Description:
- refactor layout checkout page

* ParentId: GC-09-FE (6)

---

app/order-ui/src/app/system/gift-card/DataTable/columns/gift-card-columns.tsx

Task Id: GC-04
Type: Fix Bug
Description:
- GC-81

* ParentId: GC-01-FE (5)

---

app/order-ui/src/components/app/sheet/create-gift-card-sheet.tsx
app/order-ui/src/components/app/sheet/update-gift-card-sheet.tsx
app/order-ui/src/components/ui/data-table.tsx
app/order-ui/src/locales/en/gift-card.json
app/order-ui/src/locales/vi/gift-card.json
app/order-ui/src/schemas/gift-card.schema.ts

Task Id: GC-73
Type: Bug
Description:
+ Fixed error message
+ Fixed Dark mode error

* ParentId: GC-82-FE (1)

---

app/order-ui/src/app/client/gift-card/components/gift-card-sheet.tsx
app/order-ui/src/app/client/gift-card/components/receiver-form.tsx
app/order-ui/src/app/client/gift-card/components/receivers-section.tsx
app/order-ui/src/app/client/gift-card/components/recipient-search-input.tsx
app/order-ui/src/locales/en/gift-card.json
app/order-ui/src/locales/vi/gift-card.json
app/order-ui/src/schemas/gift-card.schema.ts

Task Id: GC-57
Type: Fix Bug
Description:
- Implement auto-fill for receiver name

 * ParentId: GC-57-FE

---

app/order-api/src/mail/mail.module.ts
app/order-api/src/mail/mail.service.ts

Task Id: OR-536-BE
Description:
- Add [Trend Coffee] for title mail

* ParentId: OR-536-BE (1)

---

app/order-ui/src/app/system/chef-order/DataTable/columns/pending-chef-orders-columns.tsx
app/order-ui/src/components/app/countdown/OrderCountdown.tsx

Fix:
- Add log to debug
- Adjust export logic to support new voucher format
- Ensure new voucher is included in hand-over summary file

Task: Export hand-over ticket for new voucher (1)

---

app/order-ui/src/app/system/chef-order/DataTable/columns/pending-chef-orders-columns.tsx
app/order-ui/src/components/app/countdown/OrderCountdown.tsx

Fix:
- Use the template directly instead of importing it.

Task: Export hand-over ticket for new voucher (2)

---

app/order-ui/src/app/system/order-history/DataTable/columns/order-history-columns.tsx

TaskId: TRE-17-FE
Description:
- Change Print Invoice button type

Task: Implement “Print Invoice” column and print action in order list (2)

---

app/order-ui/src/app/system/order-history/DataTable/columns/order-history-columns.tsx

Description:
- Change Print Invoice button type

TaskId: TRE-17 (FE)-Implement “Print Invoice” column and print action in order list (2) 

---

app/order-ui/src/app/client/gift-card/components/gift-card-item.tsx
app/order-ui/src/app/layouts/client/components/bottom-bar.tsx
app/order-ui/src/components/app/dialog/gift-card-selected-dialog.tsx
app/order-ui/src/components/app/drawer/gift-card-selected-drawer.tsx

Task Id: Image size
Type: Fix Bug
Description:
- Added whitespace-nowrap to NavLink in BottomBar.
- Replaced FileText icon with Gift in GiftCardSelectedDialog

* ParentId: GC-05-FE (7)

---

app/order-ui/src/app/system/chef-order/DataTable/columns/pending-chef-orders-columns.tsx
app/order-ui/src/utils/printer.ts

Type: Bug
Description:
-  Auto-close kitchen print tab after printing

TaskId: TRE-18 auto-close kitchen print tab after printing (1)

---

app/order-ui/src/app/system/menu/components/system-menus.tsx

Type: Bugs
Description:
- Adjusted flex/grid layout for better responsiveness
- Tested with long item names, discounted prices, and mobile view

TaskId: TRE-23-Fix layout break in price display on menu items (1)

---

app/order-api/package.json
app/order-api/src/gift-card-modules/balance/balance.service.ts
app/order-api/src/gift-card-modules/balance/entities/balance.entity.ts
app/order-api/src/gift-card-modules/card-order/card-order.service.ts
app/order-api/src/migrations/v3.0.0-06-1750636336155-init-balance-migration-data.ts

Task Id: GC-89
Description:
+ Init balance migration data
+ Update fetch balance response by field

* ParentId: GC-14-BE (1)

---

app/order-ui/src/app/system/chef-order/DataTable/columns/pending-chef-orders-columns.tsx
app/order-ui/src/types/area.type.ts
app/order-ui/src/types/chef-order.type.ts

Description:
- Added note section with clear vertical spacing for visual separation

TaskId: TRE-29-Display overall order note on kitchen receipt with spacing and fallback (1)

---

app/order-ui/src/app/client/home/components/banner.tsx
app/order-ui/src/app/client/home/components/slider-menu.tsx
app/order-ui/src/app/client/home/page.tsx
app/order-ui/src/app/layouts/client/components/client-footer.tsx
app/order-ui/src/constants/env.ts

Description:
- Made banner section responsive and added auto-slide carousel behavior
- Refactored hardcoded URLs into environment variables (.env)

TaskId: TRE-30: update landing page with responsive banner, autoplay video, and contact section part 2 (1)

---

app/order-api/public/templates/temporary-invoice.ejs
app/order-api/src/invoice/invoice.service.ts

Task Id: OR-553-BE
Type: Bug
Description:
- Fix export temporary invoice

* ParentId: OR-553-BE (2)

---

app/order-ui/src/constants/env.ts

Type: Bugs
Description:
- Modify fanpageUrl in env.ts file

TaskId: TRE-34: update landing page with contact section (1)

---

app/order-ui/src/app/system/dishes/DataTable/columns/product-columns.tsx
app/order-ui/src/components/app/form/create-product-form.tsx
app/order-ui/src/components/app/form/update-product-form.tsx
app/order-ui/src/components/app/switch/index.tsx
app/order-ui/src/components/app/switch/is-combo-switch.tsx
app/order-ui/src/locales/en/product.json
app/order-ui/src/locales/vi/product.json
app/order-ui/src/schemas/product.schema.ts
app/order-ui/src/tests/api/product.test.ts
app/order-ui/src/types/product.type.ts

Description:
- Added `isCombo` checkbox to product creation and editing forms

TaskId: TRE-33 add isCombo field to product create and update forms (1)

---

app/order-ui/src/api/gift-card.ts
app/order-ui/src/app/client/gift-card/components/draggable-gift-card-button.tsx
app/order-ui/src/app/client/gift-card/components/gift-card-sheet.tsx
app/order-ui/src/app/client/gift-card/components/single-gift-card-display.tsx
app/order-ui/src/components/app/dialog/gift-card-selected-dialog.tsx
app/order-ui/src/components/app/drawer/gift-card-selected-drawer.tsx
app/order-ui/src/components/ui/quantity-control.tsx
app/order-ui/src/hooks/use-gift-card.ts
app/order-ui/src/locales/en/gift-card.json
app/order-ui/src/locales/en/toast.json
app/order-ui/src/locales/vi/gift-card.json
app/order-ui/src/locales/vi/toast.json
app/order-ui/src/stores/gift-card.store.ts
app/order-ui/src/types/card-order.type.ts
app/order-ui/src/utils/toast.ts

Task Id: BUG-048, BUG-049, BUG-051
Type: Fix Bug
Description:
- GC-90
- GC-91
- GC-93

* ParentId: GC-08-FE (7)

---

app/order-ui/src/app/client/home/components/banner.tsx
app/order-ui/src/app/client/home/page.tsx

Type: Bugs
Description:
- Ensure slide transition occurs at a fixed interval

TaskId: TRE-36-FE (1) fix banner auto-slide not working on landing page

---

app/order-api/src/app/app.validation.ts
app/order-api/src/auth/auth.service.spec.ts
app/order-api/src/gift-card-modules/gift-card.module.ts
app/order-api/src/gift-card-modules/point-transaction/dto/create-point-transaction.dto.ts
app/order-api/src/gift-card-modules/point-transaction/dto/find-all-point-transaction.dto.ts
app/order-api/src/gift-card-modules/point-transaction/dto/point-transaction-response.dto.ts
app/order-api/src/gift-card-modules/point-transaction/dto/update-point-transaction.dto.ts
app/order-api/src/gift-card-modules/point-transaction/entities/point-transaction.entity.ts
app/order-api/src/gift-card-modules/point-transaction/entities/point-transaction.enum.ts
app/order-api/src/gift-card-modules/point-transaction/point-transaction.controller.ts
app/order-api/src/gift-card-modules/point-transaction/point-transaction.exception.ts
app/order-api/src/gift-card-modules/point-transaction/point-transaction.mapper.ts
app/order-api/src/gift-card-modules/point-transaction/point-transaction.service.ts
app/order-api/src/gift-card-modules/point-transaction/point-transaction.validation.ts
app/order-api/src/migrations/v3.0.0-07-1750679470362-create-point-transaction-migration.ts
app/order-api/src/shared/utils/obj.util.ts
app/order-api/src/user/user.entity.ts

Task Id: GC-89
Description:
+ Init point transaction migration
+ Get all/ get by transaction API

* ParentId: GC-14-BE (2)

---

app/order-api/src/auth/auth.service.spec.ts
app/order-api/src/gift-card-modules/gift-card.module.ts
app/order-api/src/gift-card-modules/point-transaction/dto/create-point-transaction.dto.ts
app/order-api/src/gift-card-modules/point-transaction/dto/point-transaction-response.dto.ts
app/order-api/src/gift-card-modules/point-transaction/entities/point-transaction.entity.ts
app/order-api/src/gift-card-modules/point-transaction/point-transaction.service.ts
app/order-api/src/gift-card-modules/point-transaction/point-transaction.validation.ts

Task Id: GC-89
Description:
+ Add res fields
+ Update create API

* ParentId: GC-14-BE (5)

---

app/order-ui/src/app/client/gift-card/checkout/[slug]/page.tsx
app/order-ui/src/components/app/countdown/GiftCardCountdown.tsx

Task Id: GC-95
Type: Fix Bug
Description:
- add gift card countdown

* ParentId: GC-94-FE (1)

---

app/order-ui/src/app/client/gift-card/components/gift-card-sheet.tsx
app/order-ui/src/app/client/gift-card/components/receiver-form.tsx
app/order-ui/src/app/client/gift-card/components/receivers-section.tsx
app/order-ui/src/app/client/gift-card/components/recipient-search-input.tsx

Task Id: BUG-051
Type: Fix Bug
Description:
- GC-93

* ParentId: GC-08-FE (8)

---

app/order-ui/src/app/client/product-detail/page.tsx
app/order-ui/src/components/app/dialog/client-add-to-cart-dialog.tsx

Type: Bugs
Description:
- Fixed incorrect price being passed when clicking "Buy Now" on menu page
- Corrected logic in product detail page where modifiers/options were not reflected in final price
- Ensured quantity defaults correctly and updates when using "Buy Now" or "Add to Cart"

TaskId: TRE-37-FE (3) Update add-to-cart flow with improved UX and logic

---

app/order-api/src/chef-order/chef-order.service.ts
app/order-api/src/chef-order/chef-order.validation.ts

Task Id: BUG-559-BE
Description:
- Hot fix: deny create manual chef order when order not paid

* ParentId: BUG-559-BE(1)

---

app/order-ui/src/components/app/sheet/create-multiple-voucher-sheet.tsx
app/order-ui/src/components/app/sheet/create-voucher-sheet.tsx
app/order-ui/src/components/app/sheet/update-voucher-sheet.tsx
app/order-ui/src/schemas/voucher.schema.ts

Type: Bugs
Description:
- Disallowed setting expiration date (`endDate`) earlier than the start date (`startDate`)
- Added frontend form validation and error message for users

TaskId: TRE-43-FE (1) Prevent creating vouchers with endDate earlier than startDate

---

app/order-ui/src/components/app/sheet/update-voucher-sheet.tsx

Type: Bugs
Description:
- Disabled editing of voucher `value` field once voucher is created

TaskId: TRE-44-FE (1) Resolve pricing inconsistency caused by voucher changes after application

---

app/order-ui/src/components/app/sheet/voucher-list-sheet-in-update-order.tsx
app/order-ui/src/components/app/sheet/voucher-list-sheet.tsx

Type: Bugs
Description:
- Updated voucher logic to show all applicable voucher base on price after promotion

TaskId: TRE-42-FE (2) Show item-specific vouchers even when cart is ineligible, with explanatory note

---

app/order-ui/src/app/client/menu/components/client-menu-item.tsx
app/order-ui/src/app/client/product-detail/page.tsx

Type: Bugs
Description:
-Modify logic in Buy now button and Add to cart button on product detail page, so the cart display the promotional price

TaskId: TRE-37 + TRE-46 (FE) (4) Discounted product shows original price in cart instead of promotional price

---

app/order-api/src/gift-card-modules/card-order/card-order.subscriber.ts

Task Id: GC-96
Description:
+ Fix crash app when card order expire

* ParentId: GC-79-BE (3)

---

app/order-ui/src/components/app/sheet/create-promotion-sheet.tsx
app/order-ui/src/components/app/sheet/create-voucher-sheet.tsx
app/order-ui/src/components/app/sheet/update-promotion-sheet.tsx
app/order-ui/src/components/app/sheet/update-voucher-sheet.tsx
app/order-ui/src/schemas/promotion.schema.ts
app/order-ui/src/schemas/voucher.schema.ts

Type: Bugs
Description:
- Enhanced the form layout for easier voucher creation and update
- Improved date picker UX for startDate and endDate
- Adjusted input spacing, labels, and validation feedback

TaskId: TRE-43-FE (2) improve UX when creating and editing vouchers

---

app/order-ui/src/components/app/select/voucher-type-select.tsx
app/order-ui/src/components/app/sheet/update-voucher-sheet.tsx

Type: Bugs
Description:
- Disable voucher type select when update

TaskId: TRE-43 + TRE-49 (FE) (4) improve UX when creating and editing vouchers

---

app/order-ui/src/app/client/menu/components/dual-range-slider.tsx
app/order-ui/src/app/client/menu/components/price-range-filter.tsx

Type: Bugs
Description:
- Improved input validation and formatting logic when change slide value

TaskId: TRE-39-FE (2) Fix price filter input behavior and value limits on menu page

---

app/order-ui/src/components/app/sheet/update-voucher-sheet.tsx

Type: Bugs
Description:
- Modify active logic switch when start date is greater than today

TaskId: TRE-43-FE (5) improve UX when creating and editing vouchers

---

app/order-ui/src/app/client/gift-card/components/recipient-search-input.tsx
app/order-ui/src/locales/en/gift-card.json
app/order-ui/src/locales/vi/gift-card.json

Task Id: BUG-052
Type: Fix Bug
Description:
- GC-105

* ParentId: GC-08-FE (9)

---

app/order-api/src/payment/payment.service.ts

Task Id: GC-96
Description:
+ update payment callback

* ParentId: GC-79-BE (7)

---

app/order-api/src/gift-card-modules/point-transaction/dto/find-all-point-transaction.dto.ts
app/order-api/src/gift-card-modules/point-transaction/point-transaction.service.ts

Task Id: GC-89
Description:
+ Add filter

* ParentId: GC-14-BE (6)

---

app/order-api/src/gift-card-modules/card-order/card-order.enum.ts
app/order-api/src/gift-card-modules/card-order/card-order.validation.ts

Task Id: GC-36
Description:
+ Add BUY type

* ParentId: GC-08-BE (13)

---

app/order-api/src/gift-card-modules/gift-card/dto/gift-card-response.dto.ts
app/order-api/src/gift-card-modules/gift-card/entities/gift-card.entity.ts
app/order-api/src/gift-card-modules/gift-card/gift-card.controller.ts
app/order-api/src/gift-card-modules/gift-card/gift-card.service.ts

Task Id: GC-89
Description:
+ Find all / find one gift card

* ParentId: GC-14-BE (7)

---

app/order-ui/src/components/app/dialog/index.tsx
app/order-ui/src/components/app/dialog/transaction-gift-card-detail-dialog.tsx
app/order-ui/src/components/app/tabscontent/customer-coin-tabs-content.tsx
app/order-ui/src/index.css
app/order-ui/src/locales/en/profile.json
app/order-ui/src/locales/vi/profile.json

Task Id: GC-88
Description:
- Add transaction gift card detail dialog

* ParentId: GC-14-FE (4)

---

app/order-ui/src/app/system/chef-order/DataTable/columns/pending-chef-orders-columns.tsx

Type: Bugs
Description:
- Fixed mismatch between ordered quantity and displayed quantity

TaskId: TRE-62-FE (1) correct item quantity display on kitchen ticket

---

app/order-api/src/gift-card-modules/card-order/dto/card-order-response.dto.ts
app/order-api/src/gift-card-modules/gift-card/dto/gift-card-response.dto.ts

Task Id: GC-89
Description:
+ Fix circular dependency.

* ParentId: GC-14-BE (8)

---

app/order-api/src/gift-card-modules/gift-card/dto/create-gift-card.dto.ts
app/order-api/src/gift-card-modules/gift-card/dto/gift-card-response.dto.ts
app/order-api/src/gift-card-modules/gift-card/gift-card.mapper.ts
app/order-api/src/gift-card-modules/gift-card/gift-card.scheduler.ts
app/order-api/src/gift-card-modules/gift-card/gift-card.service.ts
app/order-api/src/gift-card-modules/gift-card/gift-card.utill.ts

Task Id: GC-96
Description:
+ Fix gift card expiring right after creation. +Fix expiration date defaulting to midnight of creation day.

* ParentId: GC-79-BE (8)

---

app/order-api/src/gift-card-modules/gift-card/entities/gift-card.entity.ts
app/order-api/src/gift-card-modules/gift-card/gift-card.mapper.ts

Task Id: GC-96
Description:
+ Fix internal error

* ParentId: GC-79-BE (9)

---

app/order-ui/src/app/client/home/components/slider-menu.tsx
app/order-ui/src/components/app/drawer/client-add-to-cart-drawer .tsx
app/order-ui/src/components/app/sheet/voucher-list-sheet.tsx
app/order-ui/src/stores/cart.store.ts

Type: Bugs
Description:
- Modify slider menu to store correct product slug instead of menu item slug

TaskId: TRE-63-FE (1) Fix for incorrect available voucher display

---

app/order-ui/src/components/app/form/create-customer-form.tsx
app/order-ui/src/components/app/form/create-employee-form.tsx
app/order-ui/src/components/app/form/register-form.tsx
app/order-ui/src/constants/regex.ts

Description:
- Modify regex validation in user registration

TaskId: TRE-65-FE (1) Modify regex validation in user registration

---

app/order-ui/src/app/client/menu/components/client-menu-item-in-update-order.tsx
app/order-ui/src/app/client/update-order/components/update-note.tsx
app/order-ui/src/app/client/update-order/components/update-order-note.tsx
app/order-ui/src/app/client/update-order/page.tsx
app/order-ui/src/components/app/dialog/remove-order-item-in-update-order-dialog.tsx
app/order-ui/src/components/app/sheet/staff-voucher-list-sheet-in-update-order.tsx
app/order-ui/src/components/app/sheet/voucher-list-sheet-in-update-order.tsx
app/order-ui/src/components/app/tabscontent/client-menu.tabscontent.tsx
app/order-ui/src/utils/toast.ts

Type: Bugs
Description:
- Modify update order page UI
- Enable remove button if voucher is used

TaskId: TRE-57-FE (1) Fix unable to remove voucher on customer order update page

---

app/order-ui/src/components/app/tabscontent/customer-coin-tabs-content.tsx

Task Id: GC-121, GC-122
Type: Fix bug
Description:
- Refactor CustomerCoinTabsContent to simplify filter handling

* ParentId: GC-109-FE (2)

---

app/order-ui/src/app/client/gift-card/page.tsx

Task Id: GC-116
Type: fix bug
Description:
- Refactor authentication check in ClientGiftCardPage to use useAuthStore

* ParentId: GC-116-FE (1)

---

app/order-ui/src/app/client/profile/page.tsx
app/order-ui/src/components/app/tabscontent/customer-coin-tabs-content.tsx

Task Id: GC-120, 123
Type: Fix Bug
Description:
- export point transaction

* ParentId: GC-107-FE (2)

---

app/order-ui/src/components/app/tabscontent/customer-coin-tabs-content.tsx

Task Id: GC-121
Type: Fix bug
Description:
- Remove initial render check

* ParentId: GC-109-FE (3)

---

app/order-ui/src/api/chef-area.ts
app/order-ui/src/app/system/chef-area/DataTable/actions/printer-action-options.tsx
app/order-ui/src/app/system/chef-area/DataTable/columns/printers-columns.tsx
app/order-ui/src/components/app/dialog/confirm-ping-printer-dialog.tsx
app/order-ui/src/components/app/dialog/delete-printer-dialog.tsx
app/order-ui/src/components/app/dialog/index.tsx
app/order-ui/src/components/app/sheet/update-printer-sheet.tsx
app/order-ui/src/components/app/switch/printer-toggle-switch.tsx
app/order-ui/src/hooks/use-chef-area.ts
app/order-ui/src/locales/en/chef-area.json
app/order-ui/src/locales/en/toast.json
app/order-ui/src/locales/vi/chef-area.json
app/order-ui/src/locales/vi/toast.json
app/order-ui/src/types/area.type.ts

Description:
- Add ping button

TaskId: TRE-64-FE (2) Implement printer management in chef area page

---

app/order-api/src/chef-order/chef-order.listener.ts

Task Id: OR-562-BE
Type: Bug
Description:
- Fix logic in chef order listener

* ParentId: OR-562-BE (1)

---

app/order-ui/src/api/gift-card.ts
app/order-ui/src/components/app/dialog/index.tsx
app/order-ui/src/components/app/dialog/use-gift-card-dialog.tsx
app/order-ui/src/components/app/dropdown/client-header-dropdown.tsx
app/order-ui/src/hooks/use-gift-card.ts
app/order-ui/src/locales/en/gift-card.json
app/order-ui/src/locales/en/sidebar.json
app/order-ui/src/locales/en/toast.json
app/order-ui/src/locales/vi/gift-card.json
app/order-ui/src/locales/vi/sidebar.json
app/order-ui/src/locales/vi/toast.json
app/order-ui/src/types/gift-card.type.ts
app/order-ui/src/utils/toast.ts

Task Id: GC-119
Type: Fix bug
Description:
- add use gift card dialog

* ParentId: GC-12-FE (1)

---

app/order-api/src/chef-order/chef-order.listener.ts
app/order-api/src/chef-order/chef-order.service.ts

Task Id: OR-563-BE
Type: Bug
Description:
- Use Promise.allSettled replace for loop when call printer

* ParentId: OR-563-BE (1)

---

app/order-api/src/auth/auth.dto.ts

Task Id: GC-96
Description:
+ Update phonenumber dto

* ParentId: GC-79-BE (11)

---

app/order-ui/src/app/client/home/components/banner.tsx
app/order-ui/src/app/system/banner/DataTable/columns/banner-columns.tsx
app/order-ui/src/components/app/dialog/upload-banner-image-dialog.tsx
app/order-ui/src/locales/en/banner.json
app/order-ui/src/locales/vi/banner.json

Description:
- Add image column

TaskId: TRE-71-FE (1) Update banner table

---

app/order-api/src/promotion/promotion.controller.ts
app/order-api/src/promotion/promotion.dto.ts
app/order-api/src/promotion/promotion.service.ts
app/order-api/src/voucher/voucher.controller.ts

Type: Feature
Description:
- handle dto and swagger of promotion to response data with pagination format

TaskId: TRE-69-BE (1) implement pagination for promotion

---

app/order-ui/src/components/app/picker/simple-date-picker.tsx
app/order-ui/src/components/app/tabscontent/customer-coin-tabs-content.tsx

Task Id: GC-137
Type: Fix bug
Description:
- Add minDate and maxDate props to SimpleDatePicker

* ParentId: GC-109-FE (4)

---

app/order-api/src/gift-card-modules/card-order/card-order.service.ts
app/order-api/src/payment/payment.service.ts

Task Id: GC-96
Description:
+ Fix calc balance error

* ParentId: GC-79-BE (12)

---

.deploy/cloud/docker-compose.yml
.deploy/dev/docker-compose.yml
.deploy/prod-for-staff/docker-compose.yml
.deploy/staging/docker-compose.yml
app/order-api/src/app/env.validation.ts

Task Id: AU-543-BE
Description:
- Update env for docker compose file

* ParentId: AU-543-BE(2)

---

app/order-api/src/payment/payment.service.ts

Task Id: GC-96
Description:
+ card order does not complete after payment is completed

* ParentId: GC-79-BE (14)

---

app/order-api/public/templates/point-transaction.ejs
app/order-api/public/templates/point-transactions.ejs

Task Id: GC-111
Description:
+ Update template

* ParentId: GC-107-BE (2)

---

app/order-api/src/auth/auth.dto.ts
app/order-api/src/auth/constants.ts

Type: Fixbug
Description:
- handle regex Vietnamese number phone and email format

TaskId: TRE-59-BE (1) validate register payload

---

app/order-api/package-lock.json
app/order-api/package.json
app/order-api/src/app/app.module.ts
app/order-api/src/gift-card-modules/balance/balance.validation.ts
app/order-api/src/gift-card-modules/gift-card/gift-card.service.ts
app/order-api/src/job/job.controller.spec.ts
app/order-api/src/job/job.module.ts
app/order-api/src/job/job.service.spec.ts
app/order-api/src/job/job.service.ts
app/order-api/src/payment/payment.constants.ts
app/order-api/src/payment/payment.controller.spec.ts
app/order-api/src/payment/payment.module.ts
app/order-api/src/payment/payment.service.spec.ts
app/order-api/src/payment/payment.service.ts
app/order-api/src/payment/strategy/point.strategy.ts
app/order-api/src/shared/services/shared-balance.service.ts
app/order-api/src/shared/services/shared-point-transaction.service.ts
app/order-api/src/shared/shared.module.ts
app/order-api/src/shared/utils/currency.util.ts

* Parent ID: GC-117-BE (1)

---

app/order-api/src/gift-card-modules/card-order/card-order.service.ts
app/order-api/src/gift-card-modules/point-transaction/entities/point-transaction.enum.ts
app/order-api/src/gift-card-modules/point-transaction/point-transaction.service.ts
app/order-api/src/gift-card-modules/point-transaction/point-transaction.validation.ts

Task Id: GC-96
Description:
+ Create 1 tracnsaction when card order type = GIFT, SELF

* ParentId: GC-79-BE (15)

---

app/order-ui/src/app/client/gift-card/checkout/success/success-page.tsx

Task Id: GC-132
Type: Fix bug
Description:
- remove button giftCard View Details

* ParentId: GC-109-FE (5)

---

app/order-ui/src/components/app/picker/simple-date-picker.tsx
app/order-ui/src/components/app/tabscontent/customer-coin-tabs-content.tsx

Task Id: GC-137
Type: Fix bug
Description:
- Support allowEmpty prop in both DatePicker and add month select for calendar

* ParentId: GC-109-FE (6)

---

.build/order-api/Dockerfile

Task Id: OPS-567
Type: Bugs
Description:
- Fix docker file: change from node:18-buster to node:18-bookworm

* ParentId: OPS-567(1)

---

app/order-ui/src/components/app/dialog/transaction-gift-card-detail-dialog.tsx
app/order-ui/src/components/app/tabscontent/customer-coin-tabs-content.tsx
app/order-ui/src/constants/point-transaction.ts
app/order-ui/src/locales/en/profile.json
app/order-ui/src/locales/vi/profile.json
app/order-ui/src/types/gift-card.type.ts

Task Id: GC-88
Description:
- Added support for CARD_ORDER type in transaction handling

* ParentId: GC-14-FE (6)

---

app/order-api/public/templates/invoice.ejs
app/order-api/src/helper/index.ts
app/order-api/src/invoice/invoice.service.ts

Task Id: GC-128
Description:
+ Update invoice

* Parent ID: GC-117-BE (2)

---

app/order-ui/src/app/system/menu/components/cart-content.tsx
app/order-ui/src/app/system/menu/components/system-menus.tsx
app/order-ui/src/app/system/update-order/components/update-order-content.tsx

Description:
- Update cart content UI

TaskId: TRE-70-FE (5) Implement customer facing display screen

---

app/order-api/public/templates/point-transaction.ejs
app/order-api/public/templates/point-transactions.ejs
app/order-api/src/gift-card-modules/point-transaction/entities/point-transaction.enum.ts
app/order-api/src/gift-card-modules/point-transaction/point-transaction.service.ts

Task Id: GC-111
Description:
+ Update col width, add data

* ParentId: GC-107-BE (4)

---

app/order-ui/src/app/client/public-order-detail/components/invoice-template.tsx
app/order-ui/src/locales/en/menu.json
app/order-ui/src/locales/vi/menu.json

Task Id: GC-127
Description:
- Update invoice template and localization for estimated total

* ParentId: GC-117-FE (3)

---

app/order-api/public/templates/invoice.ejs

Task Id: GC-128
Description:
+ Add total discount row

* Parent ID: GC-117-BE (3)

---

app/order-api/src/printer/printer.worker.ts

Task Id: OR-565-BE
Description:
+ Add log in worker

* ParentId: OR-565-BE (4)

---

app/order-api/src/invoice/invoice.scheduler.ts

Task Id: OR-570-BE
Type: Bug
Description:
+ Disable invoice scheduler

* ParentId: OR-570-BE (1)

---

app/order-api/src/invoice/invoice.scheduler.ts

Task Id: OR-570-BE
Type: Bug
Description:
+ Disable invoice scheduler

* ParentId: hotfix OR-570-BE (1)

---

app/order-ui/src/components/app/dialog/use-gift-card-dialog.tsx

Task Id: GC-153
Type: Fix bug
Description:
- Enhance mobile responsiveness of UseGiftCardDialog component

* ParentId: GC-12-FE (2)

---

app/order-api/src/auth/auth.dto.ts

Type: Fixbug
Description:
- handle regex Vietnamese number phone and email format

TaskId: TRE-59-BE (2) validate register payload

---

app/order-ui/src/app/client/home/components/slider-menu.tsx
app/order-ui/src/app/client/product-detail/page.tsx
app/order-ui/src/components/app/sheet/voucher-list-sheet.tsx

Type: Bugs
Description:
- Update init ordering phase logic

TaskId: TRE-77-FE (1) Fix issue where vouchers are not visible to customers

---

app/order-api/src/gift-card-modules/feature-flag/dto/bulk-update-feature-flag.dto.ts
app/order-api/src/gift-card-modules/feature-flag/dto/feature-flag-response.dto.ts
app/order-api/src/gift-card-modules/feature-flag/dto/feature-group-response.dto.ts
app/order-api/src/gift-card-modules/feature-flag/dto/query-feature-flag.dto.ts
app/order-api/src/gift-card-modules/feature-flag/entities/feature-flag.entity.ts
app/order-api/src/gift-card-modules/feature-flag/entities/feature-group.entity.ts
app/order-api/src/gift-card-modules/feature-flag/feature-flag.constant.ts
app/order-api/src/gift-card-modules/feature-flag/feature-flag.controller.ts
app/order-api/src/gift-card-modules/feature-flag/feature-flag.exception.ts
app/order-api/src/gift-card-modules/feature-flag/feature-flag.mapper.ts
app/order-api/src/gift-card-modules/feature-flag/feature-flag.service.ts
app/order-api/src/gift-card-modules/feature-flag/feature-flag.validation.ts
app/order-api/src/gift-card-modules/gift-card.module.ts
app/order-api/src/migrations/v3.0.0-09-1753253271699-init-feature-flag-schema-migration.ts
app/order-api/src/payment/payment.service.ts

* Parent ID: GC-145-BE (1)

---

app/order-api/src/order/order.service.ts
app/order-api/src/voucher/voucher.utils.ts

Task Id: OR-542-BE
Description:
- Update code for update voucher order, update order item

* ParentId: OR-542-BE (2)

---

app/order-api/src/gift-card-modules/feature-flag/feature-flag.controller.ts

Task Id: GC-151
Description:
+ Add ApiBearerAuth decorator

* Parent ID: GC-145-BE (2)

---

app/order-api/package-lock.json
app/order-api/package.json
app/order-api/public/templates/invoice.ejs
app/order-api/src/app/app.module.ts
app/order-api/src/gift-card-modules/balance/balance.validation.ts
app/order-api/src/gift-card-modules/gift-card/gift-card.service.ts
app/order-api/src/helper/index.ts
app/order-api/src/invoice/invoice.service.ts
app/order-api/src/job/job.controller.spec.ts
app/order-api/src/job/job.module.ts
app/order-api/src/job/job.service.spec.ts
app/order-api/src/job/job.service.ts
app/order-api/src/payment/payment.constants.ts
app/order-api/src/payment/payment.controller.spec.ts
app/order-api/src/payment/payment.module.ts
app/order-api/src/payment/payment.service.spec.ts
app/order-api/src/payment/payment.service.ts
app/order-api/src/payment/strategy/point.strategy.ts
app/order-api/src/shared/services/shared-balance.service.ts
app/order-api/src/shared/services/shared-point-transaction.service.ts
app/order-api/src/shared/shared.module.ts
app/order-api/src/shared/utils/currency.util.ts

* Parent ID: GC-117-BE (1) 

---

app/order-api/src/gift-card-modules/card-order/card-order.service.ts
app/order-api/src/gift-card-modules/feature-flag/dto/find-feature-flag.dto.ts
app/order-api/src/gift-card-modules/feature-flag/feature-flag.controller.ts
app/order-api/src/gift-card-modules/feature-flag/feature-flag.service.ts
app/order-api/src/gift-card-modules/feature-flag/feature-flag.validation.ts
app/order-api/src/gift-card-modules/feature-flag/feature-group.constant.ts
app/order-api/src/gift-card-modules/gift-card.module.ts
app/order-api/src/gift-card-modules/gift-card/gift-card.service.ts

Task Id: GC-151
Description:
+ Add API
+ Handle lock features

* Parent ID: GC-145-BE (3)

---

app/order-ui/src/app/client/profile/page.tsx

Task Id: GC-153
Description:
- Add css

* ParentId: GC-12-FE (3)

---

app/order-ui/src/app/system/feature-lock-management/index.tsx
app/order-ui/src/app/system/feature-lock-management/page.tsx
app/order-ui/src/app/system/gift-card-feature-flag/index.tsx
app/order-ui/src/constants/route.ts
app/order-ui/src/locales/en/gift-card.json
app/order-ui/src/locales/en/helmet.json
app/order-ui/src/locales/en/route.json
app/order-ui/src/locales/en/sidebar.json
app/order-ui/src/locales/vi/gift-card.json
app/order-ui/src/locales/vi/helmet.json
app/order-ui/src/locales/vi/route.json
app/order-ui/src/locales/vi/sidebar.json
app/order-ui/src/router/index.tsx
app/order-ui/src/router/loadable.tsx

Task Id: GC-159 GC-160 GC-161
Type: Fix Bug
Description:
- rename Gift Card Feature Flag to Feature Lock Management and update related routes and translations

* ParentId: GC-145-FE (3)

---

app/order-ui/src/app/system/feature-lock-management/page.tsx
app/order-ui/src/locales/en/common.json
app/order-ui/src/locales/vi/common.json

Task Id: GC-161
Type: Fix Bug
Description:
- Add reset functionality and translations for feature lock management

* ParentId: GC-145-FE (4)

---

app/order-ui/src/app/client/menu/components/client-menu-item.tsx
app/order-ui/src/components/app/sheet/staff-voucher-list-sheet-in-update-order-with-local-storage.tsx
app/order-ui/src/components/app/sheet/staff-voucher-list-sheet.tsx
app/order-ui/src/components/app/sheet/voucher-list-sheet.tsx

Description:
- Update applying voucher logic

TaskId: TRE-79-FE (2) Implement support for additional voucher type

---

app/order-api/public/templates/invoice.ejs
app/order-api/src/job/job.service.ts
app/order-api/src/pdf/pdf.service.ts
app/order-api/src/printer/strategy/esc-pos-printer.strategy.ts

Description:
- Fix print bill too long

* ParentId: OR-573-BE (4)

---

app/order-api/src/gift-card-modules/point-transaction/dto/export-all-point-transaction.dto.ts
app/order-api/src/gift-card-modules/point-transaction/point-transaction.service.ts

* Parent ID: GC-149-BE (1)

---

app/order-ui/src/api/point-transaction.ts
app/order-ui/src/hooks/use-point-transaction.ts

Task Id: GC-165
Description:
- export functionality for point transactions by adding date and type filters

* ParentId: GC-149-FE (1)

---

app/order-api/src/invoice/invoice.controller.ts

Description:
- Add api export invoice png

* ParentId: OR-573-BE (6)

---

app/order-api/public/templates/invoice.ejs
app/order-api/src/pdf/pdf.service.ts

Description:
- Fix viewport export png

* ParentId: OR-573-BE (7)

---

app/order-api/src/gift-card-modules/gift-card/dto/find-all-gift-card.dto.ts
app/order-api/src/gift-card-modules/gift-card/dto/gift-card-response.dto.ts
app/order-api/src/gift-card-modules/gift-card/entities/gift-card.entity.ts
app/order-api/src/gift-card-modules/gift-card/gift-card.controller.ts
app/order-api/src/gift-card-modules/gift-card/gift-card.service.ts

* Parent ID: GC-11-BE (1)

---

app/order-api/public/templates/invoice.ejs

Description:
- Fix invoice template 3nd

* ParentId: OR-573-BE (12)

---

app/order-ui/src/app/system/chef-order/DataTable/columns/pending-chef-orders-columns.tsx
app/order-ui/src/app/system/order-history/DataTable/columns/order-history-columns.tsx

Description:
- Modify condition to show re print button

TaskId: TRE-80-FE (3) Display print jobs invoice label in chef area and order management pages

---

app/order-ui/src/app/system/chef-order/DataTable/columns/pending-chef-orders-columns.tsx
app/order-ui/src/app/system/order-history/DataTable/columns/order-history-columns.tsx

Description:
- Delete duplicate export invoice button
- Not show label printer status if value is null

TaskId: TRE-80-FE (4) Display print jobs invoice label in chef area and order management pages

---

app/order-api/public/templates/invoice.ejs

Description:
- Fix invoice template 4th

* ParentId: OR-573-BE (13)

---

app/order-api/public/templates/invoice.ejs

Description:
- Fix invoice template 5th

* ParentId: OR-573-BE (14)

---

app/order-api/public/templates/point-transactions.ejs
app/order-api/src/gift-card-modules/balance/balance.service.ts
app/order-api/src/gift-card-modules/card-order/card-order.service.ts
app/order-api/src/gift-card-modules/gift-card.module.ts
app/order-api/src/gift-card-modules/gift-card/gift-card.service.ts
app/order-api/src/gift-card-modules/point-transaction/dto/create-point-transaction.dto.ts
app/order-api/src/gift-card-modules/point-transaction/entities/point-transaction.entity.ts
app/order-api/src/gift-card-modules/point-transaction/point-transaction.service.ts
app/order-api/src/migrations/v3.0.0-10-1753950822479-update-point-transaction-schema-migration.ts
app/order-api/src/pdf/pdf.service.ts
app/order-api/src/shared/services/shared-balance.service.ts
app/order-api/src/shared/services/shared-point-transaction.service.ts

Task Id: GC-185
Description:
- Update template

* ParentId: GC-146-BE (1) 

---

app/order-ui/src/components/app/tabscontent/customer-coin-tabs-content.tsx

Task Id: GC-163
Description:
- set default filter states for date range in CustomerCoinTabsContent

* ParentId: GC-148-FE (1)

---

app/order-api/src/app/app.constants.ts
app/order-api/src/branch-revenue/branch-revenue.module.ts
app/order-api/src/branch-revenue/branch-revenue.scheduler.ts
app/order-api/src/branch-revenue/branch-revenue.service.ts

Task Id: OR-575-BE
Description:
- Implement distribute lock for auto update branch revenue every day

* ParentId: OR-575-BE (1)

---

app/order-api/src/branch-revenue/branch-revenue.scheduler.ts

Task Id: OR-576-BE
Description:
+ Increase lock time for refresh branch revenue every day

* Parent ID: OR-576-BE (1)

---

app/order-ui/src/components/app/dialog/client-confirm-update-order-dialog.tsx
app/order-ui/src/components/app/dialog/confirm-update-order-dialog.tsx

Description:
- Fix duplicate order item when updating order

TaskId: TRE-79-FE (4) Implement support for additional voucher type

---

app/order-api/src/voucher/voucher.utils.ts
app/order-api/src/voucher/voucher.validation.ts

Task Id: VC-517-BE
Description: add verify phone number when validate usage voucher

* ParentId: VC-517-BE (4)

---

app/order-ui/src/components/app/tabscontent/customer-info.tabscontent.tsx

Type: Bugs
Description:
- Fix invalid date in dob form in profile page

TaskId: TRE-87-FE (2) Fix field of update profile is not format with system

---

app/order-ui/src/app/system/dishes/product-tab.tsx
app/order-ui/src/app/system/users/DataTable/actions/employee-filter.tsx
app/order-ui/src/app/system/users/page.tsx

Type: Bugs
Description:
- Fix role filter
- Add catalog filter in product table

TaskId: TRE-115-FE (1) The data is complete but the filter for each type does not produce the data

---

app/order-ui/src/app/client/gift-card/components/gift-card-sheet.tsx
app/order-ui/src/components/app/dialog/gift-card-selected-dialog.tsx
app/order-ui/src/components/app/drawer/gift-card-selected-drawer.tsx
app/order-ui/src/components/app/sheet/update-gift-card-sheet.tsx
app/order-ui/src/hooks/use-gift-card.ts
app/order-ui/src/stores/gift-card.store.ts
app/order-ui/src/types/card-order.type.ts
app/order-ui/src/types/gift-card.type.ts

Task Id: GC-188
Description:
- UpdateGiftCard functionality with version handling and error management

* ParentId: GC-114-FE (1)

---

app/order-api/public/templates/point-transactions.ejs

Task Id: GC-189, GC-190
Description:
+ Fix typo
+ Remove total and extra balance row

* ParentId: GC-146-BE (3)

---

app/order-api/src/db/db.controller.ts
app/order-api/src/db/db.service.ts

Task Id: TRE-131-BE
Description:
- Add api download backup file

* Parent ID: TRE-131-BE (1) - Fix backup data

---

app/order-ui/src/components/app/dialog/client-add-to-cart-dialog.tsx

Description:
- Add quantity select to client add to cart dialog
- Modify add to cart dialog layout

TaskId: TRE-88-FE (1) Add quantity select to client add to cart dialog

---

app/order-ui/src/components/app/tabs/customer-profile.tabs.tsx

Task Id: GC-176
Description:
- add CustomerGiftCardTabsContent to profile tabs

* ParentId: GC-167-FE (4)

---

app/order-ui/src/app/client/menu/components/price-range-filter.tsx

Type: Bugs
Description:
- Update price slider change value when using

TaskId: TRE-147-FE (2) Menu filter not match

---

app/order-ui/src/app/client/cart/page.tsx
app/order-ui/src/components/app/input/cart-note-input.tsx
app/order-ui/src/components/app/input/order-note-input.tsx
app/order-ui/src/components/app/select/product-variant-select.tsx

Type: Bugs
Description:
- Update cart page UI on mobile

TaskId: TRE-139-FE (1) Fix bottom bar display issue in cart page on mobile

---

app/order-api/src/invoice/invoice.controller.ts
app/order-api/src/invoice/invoice.service.ts
app/order-api/src/job/job.service.ts

Task Id: TRE-143-BE
Type: Hotfix
Description:
- Disable send invoice to mail
- Create invoice when payment paid
- Add condition to export invoice: order paid, completed, shipping
- Add function in invoice service to modify data error: voucher value in invoice; update status, reference number for invoice have order paid; create invoice for paid order without invoice

* ParentId: TRE-143-BE (1)

---

app/order-ui/src/app/client/home/components/slider-menu.tsx
app/order-ui/src/app/client/menu/components/client-menu-item.tsx
app/order-ui/src/app/client/product-detail/page.tsx
app/order-ui/src/app/system/menu/components/system-menus.tsx
app/order-ui/src/components/app/dialog/add-to-cart-dialog.tsx
app/order-ui/src/components/app/dialog/client-add-to-cart-dialog.tsx
app/order-ui/src/components/app/drawer/system-add-to-cart-drawer.tsx

Type: Bugs
Description:
- Update logic when init ordering data

TaskId: TRE-149-FE (1) Fix issue where available vouchers are not displayed when add to cart from client side

---

app/order-api/src/menu/menu.service.ts

Task Id: TRE-148-BE
Type: Bugs
Description:
- Fix filter product in menu

* Parent ID: TRE-148-BE (1)

---

app/order-api/src/order-item/order-item.service.ts
app/order-api/src/order/order.dto.ts
app/order-api/src/order/order.service.spec.ts
app/order-api/src/order/order.service.ts
app/order-api/src/order/order.utils.ts

Task Id: TRE-154-BE
Description:
- Fix original subtotal in order

* Parent ID: TRE-154-BE (1)

---

app/order-ui/src/components/app/dialog/logout-dialog.tsx

Type: Bugs
Description:
- Reset menu filter when log out

TaskId: TRE-167-FE (1) Menu filter is not reset when log out

---

app/order-ui/src/locales/en/menu.json

Type: Bugs
Description:
- Update button layout in client order list page

TaskId: TRE-159-FE (1) Order list button layout error

---

app/order-ui/src/components/app/dialog/logout-dialog.tsx

Type: Bugs
Description:
- Reset menu filter when log out

TaskId: TRE-167-FE (1) FMenu filter is not reset when log out

---

app/order-api/src/branch-revenue/branch-revenue.service.ts

Task Id: TRE-180-BE
Type: Bugs
Description:
- Fix duplicate branch revenue by hour

* Parent ID: TRE-180-BE (1)

---

app/order-ui/src/app/client/menu/components/client-menu-item-in-update-order.tsx
app/order-ui/src/app/client/menu/components/menus-in-update-order.tsx
app/order-ui/src/app/client/update-order/page.tsx
app/order-ui/src/app/system/menu/components/system-menus-in-update-order.tsx
app/order-ui/src/app/system/update-order/page.tsx
app/order-ui/src/components/app/badge/promotion-tag.tsx
app/order-ui/src/components/app/dialog/client-confirm-update-order-dialog.tsx
app/order-ui/src/components/app/dialog/staff-confirm-update-order-dialog.tsx
app/order-ui/src/components/app/dialog/update-order-item-dialog.tsx
app/order-ui/src/components/app/drawer/client-add-to-cart-drawer .tsx
app/order-ui/src/components/app/select/client-table-select-in-update-order.tsx
app/order-ui/src/components/app/tabs/client-menu.tabs .tsx
app/order-ui/src/components/app/tabs/system-menu-in-update-order.tabs.tsx
app/order-ui/src/components/app/tabscontent/client-menu.tabscontent.tsx
app/order-ui/src/components/app/tabscontent/system-menu-in-update-order.tabscontent.tsx
app/order-ui/src/stores/order-flow.store.ts
app/order-ui/src/types/dish.type.ts
app/order-ui/src/utils/order-comparison.ts

Description:
- Update logic when adding new item to the order

TaskId: TRE-179-FE (1) Fix update order item

---

app/order-api/src/gift-card-modules/card-order/card-order.service.ts
app/order-api/src/gift-card-modules/gift-card/gift-card.service.ts

Task Id: GC-174
Description:
+ Update new workflow

* Parent ID: GC-11-BE (3)

---

app/order-ui/src/app/system/customers/page.tsx
app/order-ui/src/app/system/users/page.tsx
app/order-ui/src/app/system/voucher/components/page.tsx
app/order-ui/src/app/system/voucher/page.tsx
app/order-ui/src/components/ui/data-table.tsx
app/order-ui/src/constants/query.ts
app/order-ui/src/hooks/use-voucher.ts
app/order-ui/src/locales/en/customer.json
app/order-ui/src/locales/en/employee.json
app/order-ui/src/locales/en/voucher.json
app/order-ui/src/locales/vi/customer.json
app/order-ui/src/locales/vi/employee.json
app/order-ui/src/locales/vi/voucher.json

Type: Bugs
Description:
- Add specific hook and check if search param exists

TaskId: TRE-145-FE (1) Fix search box not works in data table

---

app/order-api/src/job/job.service.ts

Task Id: TRE-170-BE
Type: Bug
Description:
- Move code create invoice to try catch, below transaction update order status

* Parent ID: TRE-170-BE (1) - Do-not-automatically-create-invoice-chef-order

---

app/order-ui/src/app/system/home/components/top-products-detail.tsx
app/order-ui/src/app/system/home/overview-detail-page.tsx
app/order-ui/src/components/app/form/revenue-filter-form.tsx
app/order-ui/src/components/app/popover/revenue-filter-popover.tsx
app/order-ui/src/stores/overview-filter.store.ts

Description:
- Reset filter value when click refresh button
- Remove paging from top branch product api

TaskId: TRE-194-FE (1) Improve filters on overview page

---

app/order-ui/src/locales/en/sidebar.json
app/order-ui/src/locales/vi/sidebar.json

Task Id: GC-194
Description:
- Update language json file

* ParentId: GC-67-FE (5)

---

app/order-ui/src/app/system/home/components/top-products-detail.tsx
app/order-ui/src/app/system/home/overview-detail-page.tsx
app/order-ui/src/components/app/form/revenue-filter-form.tsx
app/order-ui/src/types/product.type.ts

Type: Bugs
Description:
- Keep filter values in local state until click submit button
- Change hasPaging field with false value

TaskId: TRE-195-FE (1) Change api field for top branch product

---

app/order-api/src/product-analysis/product-analysis.service.ts

Task Id: TRE-101-BE
Description:
- Fix paging for product analysis

* Parent ID: TRE-101-BE (4)

---

app/order-api/src/gift-card-modules/card-order/card-order.service.ts
app/order-api/src/gift-card-modules/gift-card/gift-card.service.ts
app/order-api/src/job/job.service.ts

Task Id: GC-189, GC-190
Description:
+ Update the current balance after updating the balance table
+ Fixed: Current balance not found when paying for café order

* ParentId: GC-146-BE (4)

---

app/order-ui/src/components/app/form/revenue-filter-form.tsx
app/order-ui/src/components/app/popover/revenue-filter-popover.tsx
app/order-ui/src/components/app/select/export-revenue-type-select.tsx

Type: Bugs
Description:
- Keep type in local state until user click submit button

TaskId: TRE-197-FE (1) Fix wrong result due to incorrect type when filtering on overview page

---

app/order-ui/src/components/app/select/system-horizontal-catalog-selector.tsx

Type: Bugs
Description:
- Refactor selection handling logic in SystemHorizontalCatalogSelect component

TaskId: TRE-176-FE (1) Refactor selection handling in SystemHorizontalCatalogSelect component

---

app/order-ui/src/components/app/select/system-horizontal-catalog-selector.tsx

Type: Bugs
Description:
- Refactor selection handling logic in SystemHorizontalCatalogSelect component

TRE-176-FE (1) Refactor selection handling in SystemHorizontalCatalogSelect component

---

app/order-ui/src/router/routes.ts

Task Id: GC-198
Description:
- re order gift card menu in sidebar routes

* ParentId: GC-16-FE (4)

---

app/order-ui/src/api/gift-card.ts
app/order-ui/src/components/app/gift-card/checkout/slug/page.tsx
app/order-ui/src/hooks/use-gift-card.ts

Task Id: GC-200
Description:
- imp api initpayment for admin

* ParentId: GC-17-FE (2)

---

app/order-api/src/gift-card-modules/card-order/card-order.service.ts

Task Id: GC-201
Description:
+ Fixed: Update card order payment status

* ParentId: GC-17-BE (2)

---

app/order-ui/src/app/system/chef-area/page.tsx
app/order-ui/src/components/app/form/update-chef-area-form.tsx
app/order-ui/src/components/app/select/branch-select.tsx
app/order-ui/src/locales/en/chef-area.json
app/order-ui/src/locales/vi/chef-area.json

Type: Bugs
Description:
- Modify permission checking logic to enable edit button correctly

TaskId: TRE-200-FE (1) Fix disabled edit button in chef area

---

app/order-api/src/payment/payment.service.ts

Task Id: TRE-157-BE
Description:
- Throw exception when remove voucher in order because voucher expired

* ParentId: TRE-157-BE (3)

---

app/order-ui/src/app/system/products/DataTable/columns/product-columns.tsx
app/order-ui/src/components/app/select/catalog-select.tsx

Type: Bugs
Description:
- Refactor product columns header and update catalog select to use query client for data retrieval

TaskId: TRE-176-FE (1) Fix not able to open update disk dialog

---

app/order-ui/src/app/system/products/DataTable/columns/product-columns.tsx
app/order-ui/src/components/app/select/catalog-select.tsx

Type: Bugs
Description:
- Refactor product columns header and update catalog select to use query client for data retrieval

TRE-176-FE (1) Fix not able to open update disk dialog

---

app/order-ui/src/components/app/sheet/update-voucher-sheet.tsx

Description:
- Add time field when update voucher

TaskId: TRE-203-FE (2) Add expiration time and expired voucher notification

---

app/order-ui/src/components/app/dialog/use-gift-card-dialog.tsx
app/order-ui/src/components/app/tabscontent/customer-gift-card-tabs-content.tsx

Task Id: GC-207
Type: Fix bug
Description:
+ Format currency
+ Refetch after successful gift card use

* ParentId: GC-11-FE (7)

---

app/order-api/src/gift-card-modules/card-order/card-order.service.ts
app/order-api/src/gift-card-modules/gift-card.module.ts
app/order-api/src/payment/payment.constants.ts
app/order-api/src/payment/payment.utils.ts
app/order-api/src/payment/strategy/bank-transfer.strategy.ts

Task Id: GC-220
Description:
+ Fix payment status wrong
+ Cancel payment before cancel order

* ParentId: GC-167-BE (3)

---

app/order-ui/src/app/client/home/page.tsx

Type: Bugs
Description:
- Refactor HomePage component to optimize data fetching and improve readability

TaskId: TRE-85-FE (1) Best seller UI dose not appear

---

app/order-ui/src/app/client/home/page.tsx

Type: Bugs
Description:
- Refactor HomePage component to optimize data fetching and improve readability

TRE-85-FE (1) Best seller UI dose not appear

---

app/order-ui/src/app/system/home/overview-detail-page.tsx
app/order-ui/src/components/app/form/revenue-filter-form.tsx
app/order-ui/src/components/app/popover/revenue-filter-popover.tsx

Description:
- Remove overview store, just keep filter data in local state

TaskId: TRE-209-FE (1) Reset filter state on reload or after submit in overview page

---

app/order-api/src/payment/payment.controller.ts

Task Id: GC-224
Description:
+ Exclude api on prod

* Parent ID: GC-223 (1)

---

app/order-ui/src/components/app/dialog/confirm-update-voucher-payment-method-dialog.tsx
app/order-ui/src/components/app/select/voucher-payment-method-select.tsx

Description:
- Modify update voucher payment method logic

TaskId: TRE-208-FE (3) Validate voucher by payment method

---

app/order-api/src/branch-revenue/branch-revenue.service.ts

Task Id: TRE-213-BE
Description:
- Add log when get branch revenue

* ParentId: TRE-213-BE (1)

---

app/order-ui/src/hooks/use-card-order.ts

Task Id: GC-228
Type: Fix bug
Description:
- update customerSlug in clean up filters logic

* ParentId: GC-226-FE (1)

---

app/order-api/src/order/order.controller.ts
app/order-api/src/order/order.service.ts

Task Id: TRE-212-BE
Description:
- Add api: update voucher order for public user

* ParentId: TRE-212-BE (1)

---

app/order-api/src/order/order.service.ts

Task Id: TRE-212-BE
Description:
- Fix update voucher order service for public user

* ParentId: TRE-212-BE (2)

---

app/order-ui/package-lock.json
app/order-ui/src/app/client/payment/page.tsx
app/order-ui/src/app/system/payment/payment-page.tsx
app/order-ui/src/components/app/radio/payment-method-radio-group.tsx
app/order-ui/src/components/app/sheet/client-voucher-list-sheet-in-payment.tsx

Type: Bugs
Description:
- Update auto-select payment method when applying voucher

TaskId: TRE-214-FE (2) Fix auto-select payment method when applying voucher

---

app/order-ui/src/app/client/payment/page.tsx
app/order-ui/src/app/system/payment/payment-page.tsx
app/order-ui/src/components/app/select/client-payment-method-select.tsx

Type: Bugs
Description:
- Update auto-select payment method when applying voucher

TaskId: TRE-214-FE (4) Fix auto-select payment method when applying voucher

---

app/order-ui/src/app/client/payment/page.tsx

Type: Bugs
Description:
- Debug

TaskId: TRE-214-FE (5) Fix auto-select payment method when applying voucher

---

app/order-ui/src/api/order.ts
app/order-ui/src/app/client/payment/page.tsx
app/order-ui/src/components/app/dialog/client-remove-voucher-when-paying-dialog.tsx
app/order-ui/src/components/app/sheet/client-voucher-list-sheet-in-payment.tsx
app/order-ui/src/components/app/sheet/voucher-list-sheet-in-update-order.tsx
app/order-ui/src/hooks/use-order.ts
app/order-ui/src/utils/http.ts

Type: Bugs
Description:
- Handle validate voucher without login

TaskId: TRE-214-FE (6) Fix auto-select payment method when applying voucher

---

app/order-ui/src/components/app/sheet/client-voucher-list-sheet-in-payment.tsx

Type: Bugs
Description:
- Add public voucher for order without login

TaskId: TRE-214-FE (8) Fix auto-select payment method when applying voucher

---

app/order-api/package-lock.json
app/order-ui/src/app/client/payment/page.tsx
app/order-ui/src/components/app/dialog/client-no-login-remove-voucher-when-paying-dialog.tsx
app/order-ui/src/components/app/dialog/client-remove-voucher-when-paying-dialog.tsx
app/order-ui/src/components/app/sheet/client-voucher-list-sheet-in-payment.tsx
app/order-ui/src/stores/order-flow.store.ts
app/order-ui/src/utils/payment-resolver.ts

Type: Bugs
Description:
- Refetch order data after remove voucher in case no login

TaskId: TRE-214-FE (12) Fix auto-select payment method when applying voucher

---

app/order-ui/src/app/client/payment/page.tsx
app/order-ui/src/components/app/dialog/client-remove-voucher-when-paying-dialog.tsx
app/order-ui/src/components/app/radio/payment-method-radio-group.tsx
app/order-ui/src/components/app/sheet/client-voucher-list-sheet-in-payment.tsx

Type: Bugs
Description:
- Re init payment data when remove voucher successful
- Only show selected voucher in voucher list in payment page

TaskId: TRE-214-FE (14) Fix auto-select payment method when applying voucher

---

app/order-ui/src/app/system/home/overview-detail-page.tsx
app/order-ui/src/components/app/form/revenue-filter-form.tsx
app/order-ui/src/components/app/picker/simple-date-picker.tsx
app/order-ui/src/components/app/popover/revenue-filter-popover.tsx
app/order-ui/src/stores/overview-filter.store.ts
app/order-ui/src/types/revenue.type.ts

Description:
- Keep filter state until press refresh button or reload page

TaskId: TRE-209-FE (2) Reset filter state on reload or after submit in overview page

---

app/order-ui/src/components/app/select/voucher-payment-method-select.tsx

Type: Bugs
Description:
- Validate only accept at least one payment method

TaskId: TRE-204-FE (2) Fix wrong paging behavior in collect discount when creating voucher

---

app/order-ui/src/app/layouts/system/components/app-sidebar.tsx
app/order-ui/src/components/app/skeleton/product-detail-skeleton.tsx
app/order-ui/src/components/ui/skeleton.tsx
app/order-ui/src/index.css

Type: Bugs
Description:
- Add custom css variable

TaskId: TRE-188-FE (1) Fix wrong skeleton color on product detail in dark mode

---

app/order-api/src/menu/menu.controller.spec.ts
app/order-api/src/menu/menu.controller.ts
app/order-api/src/menu/menu.module.ts
app/order-api/src/menu/menu.service.spec.ts
app/order-api/src/menu/menu.service.ts
app/order-api/src/menu/menu.validation.ts
app/order-api/src/migrations/1757061896756-add-is-gift-for-product-entity.ts
app/order-api/src/order-item/order-item.controller.ts
app/order-api/src/order-item/order-item.service.ts
app/order-api/src/order/order.controller.spec.ts
app/order-api/src/order/order.controller.ts
app/order-api/src/order/order.service.ts
app/order-api/src/order/order.validation.ts
app/order-api/src/product/product.controller.spec.ts
app/order-api/src/product/product.dto.ts
app/order-api/src/product/product.entity.ts
app/order-api/src/product/product.service.spec.ts
app/order-api/src/product/product.service.ts

Task Id: TRE-158-BE
Description:
- Add gift product - hidden product

* ParentId: TRE-158-BE (1)

---

app/order-ui/src/app/system/products/DataTable/columns/product-columns.tsx
app/order-ui/src/components/app/form/create-product-form.tsx
app/order-ui/src/components/app/form/update-product-form.tsx
app/order-ui/src/components/app/switch/index.tsx
app/order-ui/src/components/app/switch/is-gift-switch.tsx
app/order-ui/src/components/app/switch/is-limit-switch.tsx
app/order-ui/src/components/app/switch/is-new-switch.tsx
app/order-ui/src/components/app/switch/is-top-sell-switch.tsx
app/order-ui/src/locales/en/product.json
app/order-ui/src/locales/vi/product.json
app/order-ui/src/schemas/product.schema.ts
app/order-ui/src/types/product.type.ts

Description:
- Add isGift field when create and update product

TaskId: TRE-218-FE (2) Implement gift product handling

---

app/order-ui/src/tests/api/menu.test.ts

Description:
- Modify menu test file

TaskId: TRE-218-FE (3) Implement gift product handling

---

app/order-ui/src/app/client/product-detail/components/slider-related-products.tsx
app/order-ui/src/app/system/menu-detail-management/page.tsx
app/order-ui/src/app/system/menu-management/DataTable/actions/menu-action-options.tsx
app/order-ui/src/components/app/tabs/system-menu-in-update-order.tabs.tsx
app/order-ui/src/components/app/tabs/system-menu.tabs.tsx
app/order-ui/src/components/app/tabscontent/client-menu.tabscontent.tsx
app/order-ui/src/components/ui/data-table.tsx

Description:
- Use private/public specific menu api base on user info in staff side

TaskId: TRE-217-FE (11) Implement loyalty point

---

app/order-ui/src/app/client/product-detail/components/slider-related-products.tsx
app/order-ui/src/app/system/menu-detail-management/page.tsx
app/order-ui/src/app/system/menu-management/DataTable/actions/menu-action-options.tsx
app/order-ui/src/components/app/tabs/system-menu-in-update-order.tabs.tsx
app/order-ui/src/components/app/tabs/system-menu.tabs.tsx
app/order-ui/src/components/app/tabscontent/client-menu.tabscontent.tsx
app/order-ui/src/components/ui/data-table.tsx

Revert "TaskId: TRE-217-FE (11) Implement loyalty point"

---

app/order-ui/src/app/client/product-detail/components/slider-related-products.tsx
app/order-ui/src/app/system/menu-detail-management/page.tsx
app/order-ui/src/app/system/menu-management/DataTable/actions/menu-action-options.tsx
app/order-ui/src/components/app/tabs/system-menu-in-update-order.tabs.tsx
app/order-ui/src/components/app/tabs/system-menu.tabs.tsx
app/order-ui/src/components/app/tabscontent/client-menu.tabscontent.tsx
app/order-ui/src/components/ui/data-table.tsx

Revert "deploy dev - TRE-217-BE (11)"

---

app/order-ui/src/app/client/home/page.tsx
app/order-ui/src/app/client/menu/page.tsx
app/order-ui/src/components/app/dialog/create-order-dialog.tsx
app/order-ui/src/hooks/use-menu.ts

Revert "TaskId: TRE-217-FE (10) Implement loyalty point"

---

app/order-ui/src/app/client/home/page.tsx
app/order-ui/src/app/client/menu/page.tsx
app/order-ui/src/components/app/dialog/create-order-dialog.tsx
app/order-ui/src/hooks/use-menu.ts

Revert "deploy dev - TRE-217-FE (10)"

---

app/order-api/src/voucher/voucher.service.ts

Task Id: TRE-219-BE
Description:
- Add credit card payment method for bulk create voucher service

* ParentId: TRE-219-BE (7)

---

app/order-api/src/voucher/voucher.module.ts
app/order-api/src/voucher/voucher.utils.ts

Task Id: TRE-232-BE
Description:
- Refix function validateVoucherUsage

* ParentId: TRE-232-BE (1)

---

app/order-ui/src/app/client/payment/page.tsx

Description:
- Implement polling order even when remove dialog shows in payment page (client side)

TaskId: TRE-230-FE (3) Implement add new payment method - Credit card

---

app/order-ui/src/app/system/menu/components/system-menus-in-update-order.tsx
app/order-ui/src/app/system/update-order/components/update-order-content.tsx
app/order-ui/src/app/system/update-order/page.tsx
app/order-ui/src/components/app/dialog/staff-confirm-update-order-dialog.tsx
app/order-ui/src/components/app/tabs/system-menu-in-update-order.tabs.tsx
app/order-ui/src/components/app/tabscontent/system-menu-in-update-order.tabscontent.tsx
app/order-ui/src/stores/order-flow.store.ts
app/order-ui/src/types/table.type.ts

Description:
- Update logic when updating order (staff side)

TaskId: TRE-229-FE (3) Implement pickup time selection for take away orders

---

app/order-ui/src/app/client/update-order/components/client-update-order-content.tsx
app/order-ui/src/components/app/dialog/client-confirm-update-order-dialog.tsx
app/order-ui/src/components/app/dialog/staff-confirm-update-order-dialog.tsx

Description:
- Be able to change order type from take out to at table when updating order (both client and staff)

TaskId: TRE-229-FE (4) Implement pickup time selection for take away orders

---

app/order-ui/src/app/system/customers/DataTable/actions/index.tsx
app/order-ui/src/app/system/customers/DataTable/actions/order-filter.tsx
app/order-ui/src/app/system/customers/DataTable/columns/customer-columns.tsx
app/order-ui/src/app/system/customers/DataTable/columns/customer-order-history-columns.tsx
app/order-ui/src/app/system/customers/DataTable/columns/index.tsx
app/order-ui/src/app/system/customers/components/customer-order-page.tsx
app/order-ui/src/app/system/customers/components/index.tsx
app/order-ui/src/components/app/select/period-of-time-select.tsx
app/order-ui/src/components/app/sheet/order-history-detail-sheet.tsx
app/order-ui/src/components/ui/utils/data-table.utils.ts
app/order-ui/src/locales/en/customer.json
app/order-ui/src/locales/en/route.json
app/order-ui/src/locales/vi/customer.json
app/order-ui/src/locales/vi/route.json
app/order-ui/src/router/index.tsx
app/order-ui/src/router/loadable.tsx

Description:
- Create customer order history page for staff and admin

TaskId: TRE-237-FE (1) Implement customer order management page for staff and admin

---

app/order-ui/src/components/app/form/register-form.tsx
app/order-ui/src/constants/regex.ts
app/order-ui/src/locales/en/auth.json
app/order-ui/src/locales/vi/auth.json
app/order-ui/src/schemas/auth.schema.ts

Description:
- Update locale files

TaskId: TRE-238-FE (2) Add full name field in user registration form

---

app/order-api/src/auth/auth.dto.ts

Task Id: TRE-241-BE
Description:
- Add birth day when register

* ParentId: TRE-241-BE (1)

---

app/order-ui/src/components/app/form/create-customer-form.tsx
app/order-ui/src/components/app/form/update-customer-form.tsx
app/order-ui/src/schemas/user.schema.ts

Description:
- Add dob field to create/update customer dialog (staff side)

TaskId: TRE-237-FE (5) Implement customer order management page for staff and admin

---

app/order-api/src/user/user.dto.ts
app/order-api/src/user/user.service.ts

Task Id: TRE-245-BE
Description:
- Add accumulated point for get all users api

* ParentId: TRE-245-BE (1)

---

app/order-api/src/auth/auth.service.ts

Task Id: TRE-233-BE
Description:
- Add address detail for branch when get profile user

* ParentId: TRE-233-BE (8)

---

app/order-api/src/google-map/dto/google-map.response.dto.ts

Task Id: TRE-233-BE
Description:
- Add placeId for Address response

* ParentId: TRE-233-BE (9)

---

app/order-api/src/app/app.module.ts
app/order-api/src/app/app.validation.ts
app/order-api/src/branch-config/branch-config.constant.ts
app/order-api/src/branch-config/branch-config.controller.spec.ts
app/order-api/src/branch-config/branch-config.controller.ts
app/order-api/src/branch-config/branch-config.dto.ts
app/order-api/src/branch-config/branch-config.entity.ts
app/order-api/src/branch-config/branch-config.exception.ts
app/order-api/src/branch-config/branch-config.mapper.ts
app/order-api/src/branch-config/branch-config.module.ts
app/order-api/src/branch-config/branch-config.service.spec.ts
app/order-api/src/branch-config/branch-config.service.ts
app/order-api/src/branch-config/branch-config.validation.ts
app/order-api/src/branch/branch.entity.ts
app/order-api/src/migrations/1758940257909-init-branch-config-entity.ts
app/order-api/src/migrations/1758945809241-add-relation-branch-and-branch-config-entity.ts

Task Id: TRE-248-BE
Description:
- Create branch config

* ParentId: TRE-248-BE (1)

---

app/order-ui/src/app/client/cart/components/map-address-selector.tsx
app/order-ui/src/app/system/order-management/DataTable/columns/order-history-columns.tsx
app/order-ui/src/app/system/update-order/components/system-map-address-selector-in-update-order.tsx
app/order-ui/src/app/system/update-order/page.tsx
app/order-ui/src/components/app/select/order-type-in-update-order-select.tsx
app/order-ui/src/components/app/select/order-type-select.tsx
app/order-ui/src/locales/en/toast.json

Description:
- Show toast for not supported distance
- Add method delivery in order management

TaskId: TRE-234-FE (3) Implement delivery address route feature

---

app/order-api/src/order/order.service.ts

Task Id: TRE-233-BE
Description:
- Fix update order

* ParentId: TRE-233-BE (13)

---

app/order-api/src/payment/payment.dto.ts
app/order-api/src/payment/payment.service.ts
app/order-api/src/payment/payment.validation.ts
app/order-api/src/payment/strategy/credit-card.strategy.ts
app/order-api/src/payment/strategy/payment.strategy.ts

Task Id: TRE-250-BE
Description:
- Add transaction id for credit card payment

*ParentId: TRE-250-BE (1)

---

app/order-ui/src/app/client/update-order/components/map-address-selector-in-update-order.tsx
app/order-ui/src/app/system/update-order/components/system-map-address-selector-in-update-order.tsx

Description:
- Update locale file

TaskId: TRE-234-FE (7) Implement delivery address route feature

---

app/order-api/src/app/app.module.ts
app/order-api/src/feature-flag-system/decorator/feature.decorator.ts
app/order-api/src/feature-flag-system/entities/feature-flag-system.entity.ts
app/order-api/src/feature-flag-system/entities/feature-system-group.entity.ts
app/order-api/src/feature-flag-system/feature-flag-system.constant.ts
app/order-api/src/feature-flag-system/feature-flag-system.controller.spec.ts
app/order-api/src/feature-flag-system/feature-flag-system.controller.ts
app/order-api/src/feature-flag-system/feature-flag-system.dto.ts
app/order-api/src/feature-flag-system/feature-flag-system.exception.ts
app/order-api/src/feature-flag-system/feature-flag-system.mapper.ts
app/order-api/src/feature-flag-system/feature-flag-system.module.ts
app/order-api/src/feature-flag-system/feature-flag-system.scheduler.ts
app/order-api/src/feature-flag-system/feature-flag-system.service.spec.ts
app/order-api/src/feature-flag-system/feature-flag-system.service.ts
app/order-api/src/feature-flag-system/feature-flag-system.validation.ts
app/order-api/src/feature-flag-system/guard/fureture.guard.ts
app/order-api/src/migrations/1758786786004-init-feature-system-group-entity.ts
app/order-api/src/migrations/1758788452044-init-feature-flag-system-entity.ts
app/order-api/src/migrations/1758789050812-add-relation-feature-system-group-and-feature-flag-system-entity.ts

Task Id: TRE-246-BE
Description:
- Init feature flag system management

* ParentId: TRE-246-BE (1)

---

app/order-ui/src/app/client/update-order/components/map-address-selector-in-update-order.tsx
app/order-ui/src/app/system/menu/components/system-menus-in-update-order.tsx
app/order-ui/src/app/system/update-order/components/system-map-address-selector-in-update-order.tsx
app/order-ui/src/app/system/update-order/page.tsx
app/order-ui/src/components/app/dialog/client-confirm-update-order-dialog.tsx
app/order-ui/src/components/app/tabs/system-menu-in-update-order.tabs.tsx
app/order-ui/src/components/app/tabscontent/system-menu-in-update-order.tabscontent.tsx

Description:
- Fix not re-init update order store after update map

TaskId: TRE-234-FE (11) Implement delivery address route feature

---

app/order-ui/src/app/client/cart/components/map-address-selector.tsx
app/order-ui/src/app/client/update-order/components/map-address-selector-in-update-order.tsx
app/order-ui/src/app/system/payment/payment-page.tsx
app/order-ui/src/app/system/update-order/components/system-map-address-selector-in-update-order.tsx
app/order-ui/src/components/app/select/system-map-address-select.tsx
app/order-ui/src/stores/order-flow.store.ts

Description:
- Fix cannot pick address directly in map
- Fix cannot change payment method when paying

TaskId: TRE-234-FE (14) Implement delivery address route feature

---

app/order-ui/src/app/system/payment/payment-page.tsx

Description:
- Fix cannot show success page when complete paying (staff side)

TaskId: TRE-234-FE (15) Implement delivery address route feature

---

app/order-api/src/feature-flag-system/feature-flag-system.service.ts

Task Id: TRE-256-BE
Description:
- Fix: disable flag when all children disabled
- Add description for children dto

* ParentId: TRE-256-BE (1)

---

app/order-ui/src/app/system/update-order/components/system-map-address-selector-in-update-order.tsx
app/order-ui/src/components/app/select/system-map-address-select.tsx
app/order-ui/src/utils/google-map.ts

Description:
- Update parseKm function logic

TaskId: TRE-234-FE (18) Implement delivery address route feature

---

app/order-api/src/app/app.module.ts
app/order-api/src/app/app.validation.ts
app/order-api/src/auth/auth.service.spec.ts
app/order-api/src/migrations/1759134317708-init-user-group-entity.ts
app/order-api/src/migrations/1759134677701-init-user-group-member-entity.ts
app/order-api/src/migrations/1759135283923-add-relation-user-group-and-user-group-member-entity.ts
app/order-api/src/migrations/1759135610652-add-relation-user-and-user-group-member-entity.ts
app/order-api/src/user-group-member/user-group-member.controller.ts
app/order-api/src/user-group-member/user-group-member.dto.ts
app/order-api/src/user-group-member/user-group-member.entity.ts
app/order-api/src/user-group-member/user-group-member.exception.ts
app/order-api/src/user-group-member/user-group-member.mapper.ts
app/order-api/src/user-group-member/user-group-member.module.ts
app/order-api/src/user-group-member/user-group-member.service.ts
app/order-api/src/user-group-member/user-group-member.validation.ts
app/order-api/src/user-group/user-group.controller.ts
app/order-api/src/user-group/user-group.dto.ts
app/order-api/src/user-group/user-group.entity.ts
app/order-api/src/user-group/user-group.exception.ts
app/order-api/src/user-group/user-group.mapper.ts
app/order-api/src/user-group/user-group.module.ts
app/order-api/src/user-group/user-group.service.ts
app/order-api/src/user-group/user-group.validation.ts
app/order-api/src/user/user.dto.ts
app/order-api/src/user/user.entity.ts
app/order-api/src/user/user.helper.ts
app/order-api/src/user/user.mapper.ts

Task Id: TRE-252-BE
Description:
- Init user group, user group member

*ParentId: TRE-252-BE (1)

---

app/order-ui/src/components/ui/data-table.tsx

Task Id: GC-251
Description:
+ FE fix

* Parent ID: GC-222 (1)

---

app/order-api/src/job/job.service.ts

Task Id: GC-237
Description:
+ Fix pt description out of sync

* Parent ID: GC-214-BE (1)

---

app/order-api/src/gift-card-modules/card-order/card-order.service.ts
app/order-api/src/gift-card-modules/card-order/card-order.validation.ts
app/order-api/src/gift-card-modules/card-order/dto/initiate-card-order-payment.dto.ts
app/order-ui/src/api/gift-card.ts
app/order-ui/src/components/app/gift-card/checkout/slug/page.tsx
app/order-ui/src/components/ui/data-table.tsx
app/order-ui/src/hooks/use-gift-card.ts

Task Id: GC-251
Description:
+ FE fix

* Parent ID: GC-222 (1) 

---

app/order-ui/src/components/app/select/branch-select.tsx

Description:
- Set default value of branch when creating employee

TaskId: TRE-257-FE (2) Add date of birth field to employee account creation form
